# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_brain_states.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window_brain_states_maker(object):
    def setupUi(self, window_brain_states_maker):
        window_brain_states_maker.setObjectName("window_brain_states_maker")
        window_brain_states_maker.resize(876, 542)
        self.centralwidget = QtWidgets.QWidget(window_brain_states_maker)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(611, 214, 250, 251))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ButtonExportToExcel = QtWidgets.QPushButton(self.tab_2)
        self.ButtonExportToExcel.setGeometry(QtCore.QRect(660, 550, 75, 23))
        self.ButtonExportToExcel.setObjectName("ButtonExportToExcel")
        self.e_11 = QtWidgets.QRadioButton(self.tab_2)
        self.e_11.setGeometry(QtCore.QRect(53, 71, 16, 17))
        self.e_11.setText("")
        self.e_11.setAutoExclusive(False)
        self.e_11.setObjectName("e_11")
        self.e_14 = QtWidgets.QRadioButton(self.tab_2)
        self.e_14.setGeometry(QtCore.QRect(83, 21, 16, 17))
        self.e_14.setText("")
        self.e_14.setChecked(True)
        self.e_14.setAutoExclusive(False)
        self.e_14.setObjectName("e_14")
        self.e_1 = QtWidgets.QRadioButton(self.tab_2)
        self.e_1.setGeometry(QtCore.QRect(43, 121, 16, 17))
        self.e_1.setText("")
        self.e_1.setAutoExclusive(False)
        self.e_1.setObjectName("e_1")
        self.e_12 = QtWidgets.QRadioButton(self.tab_2)
        self.e_12.setGeometry(QtCore.QRect(73, 51, 16, 17))
        self.e_12.setText("")
        self.e_12.setAutoExclusive(False)
        self.e_12.setObjectName("e_12")
        self.e_9 = QtWidgets.QRadioButton(self.tab_2)
        self.e_9.setGeometry(QtCore.QRect(73, 91, 16, 17))
        self.e_9.setText("")
        self.e_9.setAutoExclusive(False)
        self.e_9.setObjectName("e_9")
        self.e_4 = QtWidgets.QRadioButton(self.tab_2)
        self.e_4.setGeometry(QtCore.QRect(43, 151, 16, 17))
        self.e_4.setText("")
        self.e_4.setAutoExclusive(False)
        self.e_4.setObjectName("e_4")
        self.e_7 = QtWidgets.QRadioButton(self.tab_2)
        self.e_7.setGeometry(QtCore.QRect(43, 181, 16, 17))
        self.e_7.setText("")
        self.e_7.setAutoExclusive(False)
        self.e_7.setObjectName("e_7")
        self.e_0 = QtWidgets.QRadioButton(self.tab_2)
        self.e_0.setGeometry(QtCore.QRect(73, 121, 16, 17))
        self.e_0.setText("")
        self.e_0.setAutoExclusive(False)
        self.e_0.setObjectName("e_0")
        self.e_3 = QtWidgets.QRadioButton(self.tab_2)
        self.e_3.setGeometry(QtCore.QRect(73, 151, 16, 17))
        self.e_3.setText("")
        self.e_3.setAutoExclusive(False)
        self.e_3.setObjectName("e_3")
        self.e_15 = QtWidgets.QRadioButton(self.tab_2)
        self.e_15.setGeometry(QtCore.QRect(103, 21, 16, 17))
        self.e_15.setText("")
        self.e_15.setAutoExclusive(False)
        self.e_15.setObjectName("e_15")
        self.e_13 = QtWidgets.QRadioButton(self.tab_2)
        self.e_13.setGeometry(QtCore.QRect(103, 51, 16, 17))
        self.e_13.setText("")
        self.e_13.setAutoExclusive(False)
        self.e_13.setObjectName("e_13")
        self.e_8 = QtWidgets.QRadioButton(self.tab_2)
        self.e_8.setGeometry(QtCore.QRect(103, 121, 16, 17))
        self.e_8.setText("")
        self.e_8.setAutoExclusive(False)
        self.e_8.setObjectName("e_8")
        self.e_10 = QtWidgets.QRadioButton(self.tab_2)
        self.e_10.setGeometry(QtCore.QRect(103, 91, 16, 17))
        self.e_10.setText("")
        self.e_10.setAutoExclusive(False)
        self.e_10.setObjectName("e_10")
        self.e_2 = QtWidgets.QRadioButton(self.tab_2)
        self.e_2.setGeometry(QtCore.QRect(103, 151, 16, 17))
        self.e_2.setText("")
        self.e_2.setAutoExclusive(False)
        self.e_2.setObjectName("e_2")
        self.e_6 = QtWidgets.QRadioButton(self.tab_2)
        self.e_6.setGeometry(QtCore.QRect(73, 181, 16, 17))
        self.e_6.setText("")
        self.e_6.setAutoExclusive(False)
        self.e_6.setObjectName("e_6")
        self.e_5 = QtWidgets.QRadioButton(self.tab_2)
        self.e_5.setGeometry(QtCore.QRect(103, 181, 16, 17))
        self.e_5.setText("")
        self.e_5.setAutoExclusive(False)
        self.e_5.setObjectName("e_5")
        self.e_29 = QtWidgets.QRadioButton(self.tab_2)
        self.e_29.setGeometry(QtCore.QRect(133, 151, 16, 17))
        self.e_29.setText("")
        self.e_29.setAutoExclusive(False)
        self.e_29.setObjectName("e_29")
        self.e_18 = QtWidgets.QRadioButton(self.tab_2)
        self.e_18.setGeometry(QtCore.QRect(133, 51, 16, 17))
        self.e_18.setText("")
        self.e_18.setAutoExclusive(False)
        self.e_18.setObjectName("e_18")
        self.e_21 = QtWidgets.QRadioButton(self.tab_2)
        self.e_21.setGeometry(QtCore.QRect(133, 91, 16, 17))
        self.e_21.setText("")
        self.e_21.setAutoExclusive(False)
        self.e_21.setObjectName("e_21")
        self.e_23 = QtWidgets.QRadioButton(self.tab_2)
        self.e_23.setGeometry(QtCore.QRect(133, 121, 16, 17))
        self.e_23.setText("")
        self.e_23.setAutoExclusive(False)
        self.e_23.setObjectName("e_23")
        self.e_16 = QtWidgets.QRadioButton(self.tab_2)
        self.e_16.setGeometry(QtCore.QRect(133, 21, 16, 17))
        self.e_16.setText("")
        self.e_16.setAutoExclusive(False)
        self.e_16.setObjectName("e_16")
        self.e_26 = QtWidgets.QRadioButton(self.tab_2)
        self.e_26.setGeometry(QtCore.QRect(133, 181, 16, 17))
        self.e_26.setText("")
        self.e_26.setAutoExclusive(False)
        self.e_26.setObjectName("e_26")
        self.e_28 = QtWidgets.QRadioButton(self.tab_2)
        self.e_28.setGeometry(QtCore.QRect(163, 151, 16, 17))
        self.e_28.setText("")
        self.e_28.setAutoExclusive(False)
        self.e_28.setObjectName("e_28")
        self.e_31 = QtWidgets.QRadioButton(self.tab_2)
        self.e_31.setGeometry(QtCore.QRect(163, 121, 16, 17))
        self.e_31.setText("")
        self.e_31.setObjectName("e_31")
        self.e_17 = QtWidgets.QRadioButton(self.tab_2)
        self.e_17.setGeometry(QtCore.QRect(153, 21, 16, 17))
        self.e_17.setToolTipDuration(10)
        self.e_17.setWhatsThis("")
        self.e_17.setAccessibleName("")
        self.e_17.setAccessibleDescription("")
        self.e_17.setText("")
        self.e_17.setAutoExclusive(False)
        self.e_17.setObjectName("e_17")
        self.e_19 = QtWidgets.QRadioButton(self.tab_2)
        self.e_19.setGeometry(QtCore.QRect(163, 51, 16, 17))
        self.e_19.setText("")
        self.e_19.setAutoExclusive(False)
        self.e_19.setObjectName("e_19")
        self.e_25 = QtWidgets.QRadioButton(self.tab_2)
        self.e_25.setGeometry(QtCore.QRect(163, 181, 16, 17))
        self.e_25.setText("")
        self.e_25.setAutoExclusive(False)
        self.e_25.setObjectName("e_25")
        self.e_22 = QtWidgets.QRadioButton(self.tab_2)
        self.e_22.setGeometry(QtCore.QRect(163, 91, 16, 17))
        self.e_22.setText("")
        self.e_22.setAutoExclusive(False)
        self.e_22.setObjectName("e_22")
        self.e_27 = QtWidgets.QRadioButton(self.tab_2)
        self.e_27.setGeometry(QtCore.QRect(193, 151, 16, 17))
        self.e_27.setText("")
        self.e_27.setAutoExclusive(False)
        self.e_27.setObjectName("e_27")
        self.e_30 = QtWidgets.QRadioButton(self.tab_2)
        self.e_30.setGeometry(QtCore.QRect(193, 121, 16, 17))
        self.e_30.setText("")
        self.e_30.setAutoExclusive(False)
        self.e_30.setObjectName("e_30")
        self.e_20 = QtWidgets.QRadioButton(self.tab_2)
        self.e_20.setGeometry(QtCore.QRect(183, 71, 16, 17))
        self.e_20.setText("")
        self.e_20.setAutoExclusive(False)
        self.e_20.setObjectName("e_20")
        self.e_24 = QtWidgets.QRadioButton(self.tab_2)
        self.e_24.setGeometry(QtCore.QRect(193, 181, 16, 17))
        self.e_24.setText("")
        self.e_24.setAutoExclusive(False)
        self.e_24.setObjectName("e_24")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(33, 11, 181, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.raise_()
        self.ButtonExportToExcel.raise_()
        self.e_11.raise_()
        self.e_14.raise_()
        self.e_1.raise_()
        self.e_12.raise_()
        self.e_9.raise_()
        self.e_4.raise_()
        self.e_7.raise_()
        self.e_0.raise_()
        self.e_3.raise_()
        self.e_15.raise_()
        self.e_13.raise_()
        self.e_8.raise_()
        self.e_10.raise_()
        self.e_2.raise_()
        self.e_6.raise_()
        self.e_5.raise_()
        self.e_29.raise_()
        self.e_18.raise_()
        self.e_21.raise_()
        self.e_23.raise_()
        self.e_16.raise_()
        self.e_26.raise_()
        self.e_28.raise_()
        self.e_31.raise_()
        self.e_17.raise_()
        self.e_19.raise_()
        self.e_25.raise_()
        self.e_22.raise_()
        self.e_27.raise_()
        self.e_30.raise_()
        self.e_20.raise_()
        self.e_24.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(30, 12, 181, 191))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.et_2 = QtWidgets.QRadioButton(self.frame_5)
        self.et_2.setGeometry(QtCore.QRect(100, 40, 16, 17))
        self.et_2.setText("")
        self.et_2.setAutoExclusive(False)
        self.et_2.setObjectName("et_2")
        self.et_5 = QtWidgets.QRadioButton(self.frame_5)
        self.et_5.setGeometry(QtCore.QRect(130, 170, 16, 17))
        self.et_5.setText("")
        self.et_5.setAutoExclusive(False)
        self.et_5.setObjectName("et_5")
        self.et_11 = QtWidgets.QRadioButton(self.frame_5)
        self.et_11.setGeometry(QtCore.QRect(40, 140, 16, 17))
        self.et_11.setText("")
        self.et_11.setAutoExclusive(False)
        self.et_11.setObjectName("et_11")
        self.et_6 = QtWidgets.QRadioButton(self.tab)
        self.et_6.setGeometry(QtCore.QRect(160, 92, 16, 17))
        self.et_6.setText("")
        self.et_6.setAutoExclusive(False)
        self.et_6.setObjectName("et_6")
        self.et_12 = QtWidgets.QRadioButton(self.tab)
        self.et_12.setGeometry(QtCore.QRect(70, 182, 16, 17))
        self.et_12.setText("")
        self.et_12.setAutoExclusive(False)
        self.et_12.setObjectName("et_12")
        self.et_13 = QtWidgets.QRadioButton(self.tab)
        self.et_13.setGeometry(QtCore.QRect(70, 92, 16, 17))
        self.et_13.setText("")
        self.et_13.setAutoExclusive(False)
        self.et_13.setObjectName("et_13")
        self.et_0 = QtWidgets.QRadioButton(self.tab)
        self.et_0.setGeometry(QtCore.QRect(160, 122, 16, 17))
        self.et_0.setText("")
        self.et_0.setObjectName("et_0")
        self.et_3 = QtWidgets.QRadioButton(self.tab)
        self.et_3.setGeometry(QtCore.QRect(160, 52, 16, 17))
        self.et_3.setText("")
        self.et_3.setAutoExclusive(False)
        self.et_3.setObjectName("et_3")
        self.et_8 = QtWidgets.QRadioButton(self.tab)
        self.et_8.setGeometry(QtCore.QRect(100, 22, 16, 17))
        self.et_8.setText("")
        self.et_8.setChecked(True)
        self.et_8.setAutoExclusive(False)
        self.et_8.setObjectName("et_8")
        self.et_4 = QtWidgets.QRadioButton(self.tab)
        self.et_4.setGeometry(QtCore.QRect(160, 152, 16, 17))
        self.et_4.setText("")
        self.et_4.setAutoExclusive(False)
        self.et_4.setObjectName("et_4")
        self.et_10 = QtWidgets.QRadioButton(self.tab)
        self.et_10.setGeometry(QtCore.QRect(70, 52, 16, 17))
        self.et_10.setText("")
        self.et_10.setAutoExclusive(False)
        self.et_10.setObjectName("et_10")
        self.et_7 = QtWidgets.QRadioButton(self.tab)
        self.et_7.setGeometry(QtCore.QRect(70, 122, 16, 17))
        self.et_7.setText("")
        self.et_7.setAutoExclusive(False)
        self.et_7.setObjectName("et_7")
        self.et_1 = QtWidgets.QRadioButton(self.tab)
        self.et_1.setGeometry(QtCore.QRect(130, 22, 16, 17))
        self.et_1.setText("")
        self.et_1.setAutoExclusive(False)
        self.et_1.setObjectName("et_1")
        self.et_9 = QtWidgets.QRadioButton(self.tab)
        self.et_9.setGeometry(QtCore.QRect(100, 52, 16, 17))
        self.et_9.setText("")
        self.et_9.setAutoExclusive(False)
        self.et_9.setObjectName("et_9")
        self.et_14 = QtWidgets.QRadioButton(self.tab)
        self.et_14.setGeometry(QtCore.QRect(215, 182, 16, 17))
        self.et_14.setText("")
        self.et_14.setAutoExclusive(False)
        self.et_14.setObjectName("et_14")
        self.et_15 = QtWidgets.QRadioButton(self.tab)
        self.et_15.setGeometry(QtCore.QRect(13, 183, 16, 17))
        self.et_15.setText("")
        self.et_15.setAutoExclusive(False)
        self.et_15.setObjectName("et_15")
        self.tabWidget.addTab(self.tab, "")
        self.frame_Experimental_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_Experimental_2.setGeometry(QtCore.QRect(0, 0, 701, 81))
        self.frame_Experimental_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental_2.setObjectName("frame_Experimental_2")
        self.ButtonAdd_IndRecords = QtWidgets.QPushButton(self.frame_Experimental_2)
        self.ButtonAdd_IndRecords.setGeometry(QtCore.QRect(10, 9, 111, 31))
        self.ButtonAdd_IndRecords.setObjectName("ButtonAdd_IndRecords")
        self.ButtonDelete_IndRecords = QtWidgets.QPushButton(self.frame_Experimental_2)
        self.ButtonDelete_IndRecords.setGeometry(QtCore.QRect(9, 41, 112, 31))
        self.ButtonDelete_IndRecords.setObjectName("ButtonDelete_IndRecords")
        self.listWidget_Indiv_recordings = QtWidgets.QListWidget(self.frame_Experimental_2)
        self.listWidget_Indiv_recordings.setGeometry(QtCore.QRect(120, 10, 571, 61))
        self.listWidget_Indiv_recordings.setObjectName("listWidget_Indiv_recordings")
        self.ButtonLoadRecordings = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonLoadRecordings.setGeometry(QtCore.QRect(710, 40, 151, 41))
        self.ButtonLoadRecordings.setObjectName("ButtonLoadRecordings")
        self.ScrollBarCurrentRecord = QtWidgets.QScrollBar(self.centralwidget)
        self.ScrollBarCurrentRecord.setGeometry(QtCore.QRect(10, 85, 81, 31))
        self.ScrollBarCurrentRecord.setOrientation(QtCore.Qt.Horizontal)
        self.ScrollBarCurrentRecord.setObjectName("ScrollBarCurrentRecord")
        self.labelCurrentRecording = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrentRecording.setGeometry(QtCore.QRect(100, 90, 761, 31))
        self.labelCurrentRecording.setText("")
        self.labelCurrentRecording.setObjectName("labelCurrentRecording")
        self.BoxBinSize = QtWidgets.QSpinBox(self.centralwidget)
        self.BoxBinSize.setGeometry(QtCore.QRect(10, 150, 71, 22))
        self.BoxBinSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BoxBinSize.setMaximum(600000)
        self.BoxBinSize.setSingleStep(1)
        self.BoxBinSize.setProperty("value", 5)
        self.BoxBinSize.setObjectName("BoxBinSize")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(87, 150, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_Tmax = QtWidgets.QLabel(self.centralwidget)
        self.label_Tmax.setGeometry(QtCore.QRect(290, 170, 71, 16))
        self.label_Tmax.setText("")
        self.label_Tmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Tmax.setObjectName("label_Tmax")
        self.radioSelectLeftHem = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSelectLeftHem.setGeometry(QtCore.QRect(750, 161, 91, 17))
        self.radioSelectLeftHem.setObjectName("radioSelectLeftHem")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(661, 130, 151, 20))
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setObjectName("label_7")
        self.radioSelectNone = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSelectNone.setGeometry(QtCore.QRect(639, 181, 111, 17))
        self.radioSelectNone.setObjectName("radioSelectNone")
        self.radioSelectAll = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSelectAll.setGeometry(QtCore.QRect(639, 161, 91, 17))
        self.radioSelectAll.setObjectName("radioSelectAll")
        self.radioSelectRightHem = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSelectRightHem.setGeometry(QtCore.QRect(750, 181, 101, 17))
        self.radioSelectRightHem.setObjectName("radioSelectRightHem")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(610, 153, 250, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(792, 13, 81, 16))
        self.label_12.setObjectName("label_12")
        self.SpinBoxSamplingRate = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxSamplingRate.setGeometry(QtCore.QRect(710, 10, 81, 24))
        self.SpinBoxSamplingRate.setDecimals(3)
        self.SpinBoxSamplingRate.setMaximum(2000.0)
        self.SpinBoxSamplingRate.setProperty("value", 125.205)
        self.SpinBoxSamplingRate.setObjectName("SpinBoxSamplingRate")
        self.Box_currentTime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Box_currentTime.setGeometry(QtCore.QRect(370, 190, 81, 31))
        self.Box_currentTime.setDecimals(1)
        self.Box_currentTime.setMaximum(1000000.0)
        self.Box_currentTime.setSingleStep(5.0)
        self.Box_currentTime.setObjectName("Box_currentTime")
        self.ScrollBar_binchange = QtWidgets.QScrollBar(self.centralwidget)
        self.ScrollBar_binchange.setGeometry(QtCore.QRect(10, 189, 351, 31))
        self.ScrollBar_binchange.setMaximum(1000000)
        self.ScrollBar_binchange.setSingleStep(5)
        self.ScrollBar_binchange.setOrientation(QtCore.Qt.Horizontal)
        self.ScrollBar_binchange.setObjectName("ScrollBar_binchange")
        self.lcd_brain_state = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_brain_state.setGeometry(QtCore.QRect(270, 350, 51, 51))
        self.lcd_brain_state.setDigitCount(1)
        self.lcd_brain_state.setProperty("intValue", 0)
        self.lcd_brain_state.setObjectName("lcd_brain_state")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(263, 322, 71, 31))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(211, 301, 91, 31))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Button_Wake = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Wake.setGeometry(QtCore.QRect(10, 240, 101, 41))
        self.Button_Wake.setObjectName("Button_Wake")
        self.Button_NoREM = QtWidgets.QPushButton(self.centralwidget)
        self.Button_NoREM.setGeometry(QtCore.QRect(10, 290, 101, 41))
        self.Button_NoREM.setObjectName("Button_NoREM")
        self.Button_REM = QtWidgets.QPushButton(self.centralwidget)
        self.Button_REM.setGeometry(QtCore.QRect(10, 340, 101, 41))
        self.Button_REM.setObjectName("Button_REM")
        self.Button_Seizure = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Seizure.setGeometry(QtCore.QRect(10, 440, 101, 41))
        self.Button_Seizure.setObjectName("Button_Seizure")
        self.Button_other = QtWidgets.QPushButton(self.centralwidget)
        self.Button_other.setGeometry(QtCore.QRect(10, 390, 101, 41))
        self.Button_other.setObjectName("Button_other")
        self.Button_ExportExcel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ExportExcel.setGeometry(QtCore.QRect(440, 350, 111, 41))
        self.Button_ExportExcel.setObjectName("Button_ExportExcel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(189, 320, 71, 31))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lcd_brain_state_previous = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_brain_state_previous.setGeometry(QtCore.QRect(200, 350, 51, 51))
        self.lcd_brain_state_previous.setDigitCount(1)
        self.lcd_brain_state_previous.setProperty("intValue", 0)
        self.lcd_brain_state_previous.setObjectName("lcd_brain_state_previous")
        self.frame.raise_()
        self.tabWidget.raise_()
        self.frame_Experimental_2.raise_()
        self.ButtonLoadRecordings.raise_()
        self.ScrollBarCurrentRecord.raise_()
        self.labelCurrentRecording.raise_()
        self.BoxBinSize.raise_()
        self.label_5.raise_()
        self.label_Tmax.raise_()
        self.radioSelectLeftHem.raise_()
        self.label_7.raise_()
        self.radioSelectNone.raise_()
        self.radioSelectAll.raise_()
        self.radioSelectRightHem.raise_()
        self.label_12.raise_()
        self.SpinBoxSamplingRate.raise_()
        self.Box_currentTime.raise_()
        self.ScrollBar_binchange.raise_()
        self.lcd_brain_state.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.Button_Wake.raise_()
        self.Button_NoREM.raise_()
        self.Button_REM.raise_()
        self.Button_Seizure.raise_()
        self.Button_other.raise_()
        self.Button_ExportExcel.raise_()
        self.label_3.raise_()
        self.lcd_brain_state_previous.raise_()
        window_brain_states_maker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window_brain_states_maker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 20))
        self.menubar.setObjectName("menubar")
        window_brain_states_maker.setMenuBar(self.menubar)

        self.retranslateUi(window_brain_states_maker)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(window_brain_states_maker)

    def retranslateUi(self, window_brain_states_maker):
        _translate = QtCore.QCoreApplication.translate
        window_brain_states_maker.setWindowTitle(_translate("window_brain_states_maker", "MainWindow"))
        self.ButtonExportToExcel.setText(_translate("window_brain_states_maker", "Export"))
        self.e_14.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>M1_FrA_LEFT</p></body></html>"))
        self.e_17.setToolTip(_translate("window_brain_states_maker", "M1_FrA_RIGHT"))
        self.e_17.setStatusTip(_translate("window_brain_states_maker", "M1_FrA_RIGHT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("window_brain_states_maker", "32 OpenEphys"))
        self.et_2.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>M2_ant</p></body></html>"))
        self.et_5.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>V1M</p></body></html>"))
        self.et_6.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>S1HL_S1FL</p></body></html>"))
        self.et_0.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>S1Tr</p></body></html>"))
        self.et_3.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>M1_ant</p></body></html>"))
        self.et_4.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>V2ML</p></body></html>"))
        self.et_1.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>M2_FrA</p></body></html>"))
        self.et_14.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>EMG_Right</p></body></html>"))
        self.et_15.setToolTip(_translate("window_brain_states_maker", "<html><head/><body><p>EMG_Left</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("window_brain_states_maker", "16 Taini"))
        self.ButtonAdd_IndRecords.setText(_translate("window_brain_states_maker", "Add folder"))
        self.ButtonDelete_IndRecords.setText(_translate("window_brain_states_maker", "Delete"))
        self.ButtonLoadRecordings.setText(_translate("window_brain_states_maker", "Load recordings"))
        self.label_5.setText(_translate("window_brain_states_maker", "Bin size to plot (secs)"))
        self.radioSelectLeftHem.setText(_translate("window_brain_states_maker", "Left Hem"))
        self.label_7.setText(_translate("window_brain_states_maker", "<html><head/><body><p align=\"center\">Channels to show</p></body></html>"))
        self.radioSelectNone.setText(_translate("window_brain_states_maker", "Select none"))
        self.radioSelectAll.setText(_translate("window_brain_states_maker", "Select all"))
        self.radioSelectRightHem.setText(_translate("window_brain_states_maker", "Right Hem"))
        self.label_12.setText(_translate("window_brain_states_maker", "Sampling R"))
        self.label.setText(_translate("window_brain_states_maker", "Current"))
        self.label_2.setText(_translate("window_brain_states_maker", "Brain States"))
        self.Button_Wake.setText(_translate("window_brain_states_maker", "Wake (0)"))
        self.Button_NoREM.setText(_translate("window_brain_states_maker", "No REM (1)"))
        self.Button_REM.setText(_translate("window_brain_states_maker", "REM (2)"))
        self.Button_Seizure.setText(_translate("window_brain_states_maker", "Seizure (4)"))
        self.Button_other.setText(_translate("window_brain_states_maker", "Other (3)"))
        self.Button_ExportExcel.setText(_translate("window_brain_states_maker", "Export Excel"))
        self.label_3.setText(_translate("window_brain_states_maker", "Previous"))

