# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_perm_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_w_perm_Analysis(object):
    def setupUi(self, w_perm_Analysis):
        w_perm_Analysis.setObjectName("w_perm_Analysis")
        w_perm_Analysis.resize(643, 564)
        self.centralwidget = QtWidgets.QWidget(w_perm_Analysis)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(461, 93, 81, 31))
        self.label_24.setObjectName("label_24")
        self.ButtonRunAll = QtWidgets.QPushButton(self.tab)
        self.ButtonRunAll.setGeometry(QtCore.QRect(290, 115, 70, 51))
        self.ButtonRunAll.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonRunAll.setObjectName("ButtonRunAll")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(527, 117, 71, 20))
        self.label_18.setObjectName("label_18")
        self.Button2PDF = QtWidgets.QPushButton(self.tab)
        self.Button2PDF.setGeometry(QtCore.QRect(506, 138, 41, 19))
        self.Button2PDF.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PDF.setObjectName("Button2PDF")
        self.frame_Experimental = QtWidgets.QFrame(self.tab)
        self.frame_Experimental.setGeometry(QtCore.QRect(10, 20, 621, 71))
        self.frame_Experimental.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental.setObjectName("frame_Experimental")
        self.ButtonSelectFolder = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButtonSelectFolder.setGeometry(QtCore.QRect(9, 19, 141, 31))
        self.ButtonSelectFolder.setObjectName("ButtonSelectFolder")
        self.ButDelFile = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButDelFile.setGeometry(QtCore.QRect(540, 20, 71, 31))
        self.ButDelFile.setObjectName("ButDelFile")
        self.labelFileSelected = QtWidgets.QLabel(self.frame_Experimental)
        self.labelFileSelected.setGeometry(QtCore.QRect(160, 19, 371, 31))
        self.labelFileSelected.setText("")
        self.labelFileSelected.setObjectName("labelFileSelected")
        self.Button2PNG = QtWidgets.QPushButton(self.tab)
        self.Button2PNG.setGeometry(QtCore.QRect(567, 138, 41, 19))
        self.Button2PNG.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PNG.setObjectName("Button2PNG")
        self.ButtonClearFigures = QtWidgets.QPushButton(self.tab)
        self.ButtonClearFigures.setGeometry(QtCore.QRect(380, 120, 91, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonClearFigures.setPalette(palette)
        self.ButtonClearFigures.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonClearFigures.setObjectName("ButtonClearFigures")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(370, 114, 251, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(12, 197, 211, 16))
        self.label_21.setObjectName("label_21")
        self.tableFrequencies = QtWidgets.QTableWidget(self.tab)
        self.tableFrequencies.setGeometry(QtCore.QRect(10, 220, 621, 281))
        self.tableFrequencies.setRowCount(50)
        self.tableFrequencies.setColumnCount(6)
        self.tableFrequencies.setObjectName("tableFrequencies")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(23, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(24, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(25, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(25, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(26, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(26, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(27, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(27, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(28, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(28, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(29, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(29, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(30, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(30, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(31, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(31, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(32, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(32, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(33, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(33, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(33, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(34, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(34, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(34, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(35, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(35, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(35, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(36, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(36, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(36, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(37, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(37, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(37, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(38, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(38, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(38, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(39, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(39, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(39, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(40, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(40, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(40, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(41, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(41, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(41, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(42, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(42, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(42, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(43, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(43, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(43, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(44, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(44, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(44, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(45, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(45, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(45, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(46, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(46, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(46, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(47, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(47, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(47, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(48, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(48, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(48, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(49, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(49, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFrequencies.setItem(49, 2, item)
        self.tableFrequencies.horizontalHeader().setVisible(False)
        self.tableFrequencies.horizontalHeader().setHighlightSections(False)
        self.tableFrequencies.verticalHeader().setVisible(False)
        self.tableFrequencies.verticalHeader().setHighlightSections(False)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 131, 171, 16))
        self.label_2.setObjectName("label_2")
        self.BoxNumberShuffles = QtWidgets.QSpinBox(self.tab)
        self.BoxNumberShuffles.setGeometry(QtCore.QRect(193, 128, 91, 22))
        self.BoxNumberShuffles.setMaximum(50000)
        self.BoxNumberShuffles.setSingleStep(500)
        self.BoxNumberShuffles.setProperty("value", 50)
        self.BoxNumberShuffles.setObjectName("BoxNumberShuffles")
        self.buttonExtra = QtWidgets.QPushButton(self.tab)
        self.buttonExtra.setGeometry(QtCore.QRect(510, 180, 106, 29))
        self.buttonExtra.setObjectName("buttonExtra")
        self.SpinBoxMinVertAxes = QtWidgets.QDoubleSpinBox(self.tab)
        self.SpinBoxMinVertAxes.setGeometry(QtCore.QRect(420, 180, 82, 30))
        self.SpinBoxMinVertAxes.setObjectName("SpinBoxMinVertAxes")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(329, 185, 101, 21))
        self.label.setObjectName("label")
        self.frame_2.raise_()
        self.label_24.raise_()
        self.ButtonRunAll.raise_()
        self.label_18.raise_()
        self.Button2PDF.raise_()
        self.frame_Experimental.raise_()
        self.Button2PNG.raise_()
        self.ButtonClearFigures.raise_()
        self.label_21.raise_()
        self.tableFrequencies.raise_()
        self.label_2.raise_()
        self.BoxNumberShuffles.raise_()
        self.buttonExtra.raise_()
        self.SpinBoxMinVertAxes.raise_()
        self.label.raise_()
        self.tabWidget.addTab(self.tab, "")
        w_perm_Analysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(w_perm_Analysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 26))
        self.menubar.setObjectName("menubar")
        w_perm_Analysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(w_perm_Analysis)
        self.statusbar.setObjectName("statusbar")
        w_perm_Analysis.setStatusBar(self.statusbar)

        self.retranslateUi(w_perm_Analysis)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(w_perm_Analysis)

    def retranslateUi(self, w_perm_Analysis):
        _translate = QtCore.QCoreApplication.translate
        w_perm_Analysis.setWindowTitle(_translate("w_perm_Analysis", "MainWindow"))
        self.label_24.setText(_translate("w_perm_Analysis", "FIGURES"))
        self.ButtonRunAll.setText(_translate("w_perm_Analysis", "RUN"))
        self.label_18.setText(_translate("w_perm_Analysis", "Export"))
        self.Button2PDF.setText(_translate("w_perm_Analysis", "PDF"))
        self.ButtonSelectFolder.setText(_translate("w_perm_Analysis", "Select folder"))
        self.ButDelFile.setText(_translate("w_perm_Analysis", "Delete"))
        self.Button2PNG.setText(_translate("w_perm_Analysis", "PNG"))
        self.ButtonClearFigures.setText(_translate("w_perm_Analysis", "Close All"))
        self.label_21.setText(_translate("w_perm_Analysis", "Frequency Analysis"))
        __sortingEnabled = self.tableFrequencies.isSortingEnabled()
        self.tableFrequencies.setSortingEnabled(False)
        item = self.tableFrequencies.item(0, 0)
        item.setText(_translate("w_perm_Analysis", "Interval Name"))
        item = self.tableFrequencies.item(0, 1)
        item.setText(_translate("w_perm_Analysis", "From (Hz)"))
        item = self.tableFrequencies.item(0, 2)
        item.setText(_translate("w_perm_Analysis", "To (Hz)"))
        item = self.tableFrequencies.item(0, 3)
        item.setText(_translate("w_perm_Analysis", "Short Distance"))
        item = self.tableFrequencies.item(0, 4)
        item.setText(_translate("w_perm_Analysis", "Long Distance"))
        item = self.tableFrequencies.item(0, 5)
        item.setText(_translate("w_perm_Analysis", "Ratio"))
        item = self.tableFrequencies.item(1, 0)
        item.setText(_translate("w_perm_Analysis", "1"))
        item = self.tableFrequencies.item(1, 1)
        item.setText(_translate("w_perm_Analysis", "1"))
        item = self.tableFrequencies.item(1, 2)
        item.setText(_translate("w_perm_Analysis", "2"))
        item = self.tableFrequencies.item(2, 0)
        item.setText(_translate("w_perm_Analysis", "2"))
        item = self.tableFrequencies.item(2, 1)
        item.setText(_translate("w_perm_Analysis", "2"))
        item = self.tableFrequencies.item(2, 2)
        item.setText(_translate("w_perm_Analysis", "3"))
        item = self.tableFrequencies.item(3, 0)
        item.setText(_translate("w_perm_Analysis", "3"))
        item = self.tableFrequencies.item(3, 1)
        item.setText(_translate("w_perm_Analysis", "3"))
        item = self.tableFrequencies.item(3, 2)
        item.setText(_translate("w_perm_Analysis", "4"))
        item = self.tableFrequencies.item(4, 0)
        item.setText(_translate("w_perm_Analysis", "4"))
        item = self.tableFrequencies.item(4, 1)
        item.setText(_translate("w_perm_Analysis", "4"))
        item = self.tableFrequencies.item(4, 2)
        item.setText(_translate("w_perm_Analysis", "5"))
        item = self.tableFrequencies.item(6, 0)
        item.setText(_translate("w_perm_Analysis", "6"))
        item = self.tableFrequencies.item(6, 1)
        item.setText(_translate("w_perm_Analysis", "6"))
        item = self.tableFrequencies.item(6, 2)
        item.setText(_translate("w_perm_Analysis", "7"))
        item = self.tableFrequencies.item(7, 0)
        item.setText(_translate("w_perm_Analysis", "7"))
        item = self.tableFrequencies.item(7, 1)
        item.setText(_translate("w_perm_Analysis", "7"))
        item = self.tableFrequencies.item(7, 2)
        item.setText(_translate("w_perm_Analysis", "8"))
        item = self.tableFrequencies.item(8, 0)
        item.setText(_translate("w_perm_Analysis", "8"))
        item = self.tableFrequencies.item(8, 1)
        item.setText(_translate("w_perm_Analysis", "8"))
        item = self.tableFrequencies.item(8, 2)
        item.setText(_translate("w_perm_Analysis", "9"))
        item = self.tableFrequencies.item(9, 0)
        item.setText(_translate("w_perm_Analysis", "9"))
        item = self.tableFrequencies.item(9, 1)
        item.setText(_translate("w_perm_Analysis", "9"))
        item = self.tableFrequencies.item(9, 2)
        item.setText(_translate("w_perm_Analysis", "10"))
        item = self.tableFrequencies.item(10, 0)
        item.setText(_translate("w_perm_Analysis", "10"))
        item = self.tableFrequencies.item(10, 1)
        item.setText(_translate("w_perm_Analysis", "10"))
        item = self.tableFrequencies.item(10, 2)
        item.setText(_translate("w_perm_Analysis", "11"))
        item = self.tableFrequencies.item(11, 0)
        item.setText(_translate("w_perm_Analysis", "11"))
        item = self.tableFrequencies.item(11, 1)
        item.setText(_translate("w_perm_Analysis", "11"))
        item = self.tableFrequencies.item(11, 2)
        item.setText(_translate("w_perm_Analysis", "12"))
        item = self.tableFrequencies.item(12, 0)
        item.setText(_translate("w_perm_Analysis", "12"))
        item = self.tableFrequencies.item(12, 1)
        item.setText(_translate("w_perm_Analysis", "12"))
        item = self.tableFrequencies.item(12, 2)
        item.setText(_translate("w_perm_Analysis", "13"))
        item = self.tableFrequencies.item(13, 0)
        item.setText(_translate("w_perm_Analysis", "13"))
        item = self.tableFrequencies.item(13, 1)
        item.setText(_translate("w_perm_Analysis", "13"))
        item = self.tableFrequencies.item(13, 2)
        item.setText(_translate("w_perm_Analysis", "14"))
        item = self.tableFrequencies.item(14, 0)
        item.setText(_translate("w_perm_Analysis", "14"))
        item = self.tableFrequencies.item(14, 1)
        item.setText(_translate("w_perm_Analysis", "14"))
        item = self.tableFrequencies.item(14, 2)
        item.setText(_translate("w_perm_Analysis", "15"))
        item = self.tableFrequencies.item(15, 0)
        item.setText(_translate("w_perm_Analysis", "15"))
        item = self.tableFrequencies.item(15, 1)
        item.setText(_translate("w_perm_Analysis", "15"))
        item = self.tableFrequencies.item(15, 2)
        item.setText(_translate("w_perm_Analysis", "16"))
        item = self.tableFrequencies.item(16, 0)
        item.setText(_translate("w_perm_Analysis", "16"))
        item = self.tableFrequencies.item(16, 1)
        item.setText(_translate("w_perm_Analysis", "16"))
        item = self.tableFrequencies.item(16, 2)
        item.setText(_translate("w_perm_Analysis", "17"))
        item = self.tableFrequencies.item(17, 0)
        item.setText(_translate("w_perm_Analysis", "17"))
        item = self.tableFrequencies.item(17, 1)
        item.setText(_translate("w_perm_Analysis", "17"))
        item = self.tableFrequencies.item(17, 2)
        item.setText(_translate("w_perm_Analysis", "18"))
        item = self.tableFrequencies.item(18, 0)
        item.setText(_translate("w_perm_Analysis", "18"))
        item = self.tableFrequencies.item(18, 1)
        item.setText(_translate("w_perm_Analysis", "18"))
        item = self.tableFrequencies.item(18, 2)
        item.setText(_translate("w_perm_Analysis", "19"))
        item = self.tableFrequencies.item(19, 0)
        item.setText(_translate("w_perm_Analysis", "19"))
        item = self.tableFrequencies.item(19, 1)
        item.setText(_translate("w_perm_Analysis", "19"))
        item = self.tableFrequencies.item(19, 2)
        item.setText(_translate("w_perm_Analysis", "20"))
        item = self.tableFrequencies.item(20, 0)
        item.setText(_translate("w_perm_Analysis", "20"))
        item = self.tableFrequencies.item(20, 1)
        item.setText(_translate("w_perm_Analysis", "20"))
        item = self.tableFrequencies.item(20, 2)
        item.setText(_translate("w_perm_Analysis", "21"))
        item = self.tableFrequencies.item(21, 0)
        item.setText(_translate("w_perm_Analysis", "21"))
        item = self.tableFrequencies.item(21, 1)
        item.setText(_translate("w_perm_Analysis", "21"))
        item = self.tableFrequencies.item(21, 2)
        item.setText(_translate("w_perm_Analysis", "22"))
        item = self.tableFrequencies.item(22, 0)
        item.setText(_translate("w_perm_Analysis", "22"))
        item = self.tableFrequencies.item(22, 1)
        item.setText(_translate("w_perm_Analysis", "22"))
        item = self.tableFrequencies.item(22, 2)
        item.setText(_translate("w_perm_Analysis", "23"))
        item = self.tableFrequencies.item(23, 0)
        item.setText(_translate("w_perm_Analysis", "23"))
        item = self.tableFrequencies.item(23, 1)
        item.setText(_translate("w_perm_Analysis", "23"))
        item = self.tableFrequencies.item(23, 2)
        item.setText(_translate("w_perm_Analysis", "24"))
        item = self.tableFrequencies.item(24, 0)
        item.setText(_translate("w_perm_Analysis", "24"))
        item = self.tableFrequencies.item(24, 1)
        item.setText(_translate("w_perm_Analysis", "24"))
        item = self.tableFrequencies.item(24, 2)
        item.setText(_translate("w_perm_Analysis", "25"))
        item = self.tableFrequencies.item(25, 0)
        item.setText(_translate("w_perm_Analysis", "25"))
        item = self.tableFrequencies.item(25, 1)
        item.setText(_translate("w_perm_Analysis", "25"))
        item = self.tableFrequencies.item(25, 2)
        item.setText(_translate("w_perm_Analysis", "26"))
        item = self.tableFrequencies.item(26, 0)
        item.setText(_translate("w_perm_Analysis", "26"))
        item = self.tableFrequencies.item(26, 1)
        item.setText(_translate("w_perm_Analysis", "26"))
        item = self.tableFrequencies.item(26, 2)
        item.setText(_translate("w_perm_Analysis", "27"))
        item = self.tableFrequencies.item(27, 0)
        item.setText(_translate("w_perm_Analysis", "27"))
        item = self.tableFrequencies.item(27, 1)
        item.setText(_translate("w_perm_Analysis", "27"))
        item = self.tableFrequencies.item(27, 2)
        item.setText(_translate("w_perm_Analysis", "28"))
        item = self.tableFrequencies.item(28, 0)
        item.setText(_translate("w_perm_Analysis", "28"))
        item = self.tableFrequencies.item(28, 1)
        item.setText(_translate("w_perm_Analysis", "28"))
        item = self.tableFrequencies.item(28, 2)
        item.setText(_translate("w_perm_Analysis", "29"))
        item = self.tableFrequencies.item(29, 0)
        item.setText(_translate("w_perm_Analysis", "29"))
        item = self.tableFrequencies.item(29, 1)
        item.setText(_translate("w_perm_Analysis", "29"))
        item = self.tableFrequencies.item(29, 2)
        item.setText(_translate("w_perm_Analysis", "30"))
        item = self.tableFrequencies.item(30, 0)
        item.setText(_translate("w_perm_Analysis", "30"))
        item = self.tableFrequencies.item(30, 1)
        item.setText(_translate("w_perm_Analysis", "30"))
        item = self.tableFrequencies.item(30, 2)
        item.setText(_translate("w_perm_Analysis", "31"))
        item = self.tableFrequencies.item(31, 0)
        item.setText(_translate("w_perm_Analysis", "31"))
        item = self.tableFrequencies.item(31, 1)
        item.setText(_translate("w_perm_Analysis", "31"))
        item = self.tableFrequencies.item(31, 2)
        item.setText(_translate("w_perm_Analysis", "32"))
        item = self.tableFrequencies.item(32, 0)
        item.setText(_translate("w_perm_Analysis", "32"))
        item = self.tableFrequencies.item(32, 1)
        item.setText(_translate("w_perm_Analysis", "32"))
        item = self.tableFrequencies.item(32, 2)
        item.setText(_translate("w_perm_Analysis", "33"))
        item = self.tableFrequencies.item(33, 0)
        item.setText(_translate("w_perm_Analysis", "33"))
        item = self.tableFrequencies.item(33, 1)
        item.setText(_translate("w_perm_Analysis", "33"))
        item = self.tableFrequencies.item(33, 2)
        item.setText(_translate("w_perm_Analysis", "34"))
        item = self.tableFrequencies.item(34, 0)
        item.setText(_translate("w_perm_Analysis", "34"))
        item = self.tableFrequencies.item(34, 1)
        item.setText(_translate("w_perm_Analysis", "34"))
        item = self.tableFrequencies.item(34, 2)
        item.setText(_translate("w_perm_Analysis", "35"))
        item = self.tableFrequencies.item(35, 0)
        item.setText(_translate("w_perm_Analysis", "35"))
        item = self.tableFrequencies.item(35, 1)
        item.setText(_translate("w_perm_Analysis", "35"))
        item = self.tableFrequencies.item(35, 2)
        item.setText(_translate("w_perm_Analysis", "36"))
        item = self.tableFrequencies.item(36, 0)
        item.setText(_translate("w_perm_Analysis", "36"))
        item = self.tableFrequencies.item(36, 1)
        item.setText(_translate("w_perm_Analysis", "36"))
        item = self.tableFrequencies.item(36, 2)
        item.setText(_translate("w_perm_Analysis", "37"))
        item = self.tableFrequencies.item(37, 0)
        item.setText(_translate("w_perm_Analysis", "37"))
        item = self.tableFrequencies.item(37, 1)
        item.setText(_translate("w_perm_Analysis", "37"))
        item = self.tableFrequencies.item(37, 2)
        item.setText(_translate("w_perm_Analysis", "38"))
        item = self.tableFrequencies.item(38, 0)
        item.setText(_translate("w_perm_Analysis", "38"))
        item = self.tableFrequencies.item(38, 1)
        item.setText(_translate("w_perm_Analysis", "38"))
        item = self.tableFrequencies.item(38, 2)
        item.setText(_translate("w_perm_Analysis", "39"))
        item = self.tableFrequencies.item(39, 0)
        item.setText(_translate("w_perm_Analysis", "39"))
        item = self.tableFrequencies.item(39, 1)
        item.setText(_translate("w_perm_Analysis", "39"))
        item = self.tableFrequencies.item(39, 2)
        item.setText(_translate("w_perm_Analysis", "40"))
        item = self.tableFrequencies.item(40, 0)
        item.setText(_translate("w_perm_Analysis", "40"))
        item = self.tableFrequencies.item(40, 1)
        item.setText(_translate("w_perm_Analysis", "40"))
        item = self.tableFrequencies.item(40, 2)
        item.setText(_translate("w_perm_Analysis", "41"))
        item = self.tableFrequencies.item(41, 0)
        item.setText(_translate("w_perm_Analysis", "41"))
        item = self.tableFrequencies.item(41, 1)
        item.setText(_translate("w_perm_Analysis", "41"))
        item = self.tableFrequencies.item(41, 2)
        item.setText(_translate("w_perm_Analysis", "42"))
        item = self.tableFrequencies.item(42, 0)
        item.setText(_translate("w_perm_Analysis", "42"))
        item = self.tableFrequencies.item(42, 1)
        item.setText(_translate("w_perm_Analysis", "42"))
        item = self.tableFrequencies.item(42, 2)
        item.setText(_translate("w_perm_Analysis", "43"))
        item = self.tableFrequencies.item(43, 0)
        item.setText(_translate("w_perm_Analysis", "43"))
        item = self.tableFrequencies.item(43, 1)
        item.setText(_translate("w_perm_Analysis", "43"))
        item = self.tableFrequencies.item(43, 2)
        item.setText(_translate("w_perm_Analysis", "44"))
        item = self.tableFrequencies.item(44, 0)
        item.setText(_translate("w_perm_Analysis", "44"))
        item = self.tableFrequencies.item(44, 1)
        item.setText(_translate("w_perm_Analysis", "44"))
        item = self.tableFrequencies.item(44, 2)
        item.setText(_translate("w_perm_Analysis", "45"))
        item = self.tableFrequencies.item(45, 0)
        item.setText(_translate("w_perm_Analysis", "45"))
        item = self.tableFrequencies.item(45, 1)
        item.setText(_translate("w_perm_Analysis", "45"))
        item = self.tableFrequencies.item(45, 2)
        item.setText(_translate("w_perm_Analysis", "46"))
        item = self.tableFrequencies.item(46, 0)
        item.setText(_translate("w_perm_Analysis", "46"))
        item = self.tableFrequencies.item(46, 1)
        item.setText(_translate("w_perm_Analysis", "46"))
        item = self.tableFrequencies.item(46, 2)
        item.setText(_translate("w_perm_Analysis", "47"))
        item = self.tableFrequencies.item(47, 0)
        item.setText(_translate("w_perm_Analysis", "47"))
        item = self.tableFrequencies.item(47, 1)
        item.setText(_translate("w_perm_Analysis", "47"))
        item = self.tableFrequencies.item(47, 2)
        item.setText(_translate("w_perm_Analysis", "48"))
        item = self.tableFrequencies.item(48, 0)
        item.setText(_translate("w_perm_Analysis", "48"))
        item = self.tableFrequencies.item(48, 1)
        item.setText(_translate("w_perm_Analysis", "48"))
        item = self.tableFrequencies.item(48, 2)
        item.setText(_translate("w_perm_Analysis", "49"))
        item = self.tableFrequencies.item(49, 0)
        item.setText(_translate("w_perm_Analysis", "49"))
        item = self.tableFrequencies.item(49, 1)
        item.setText(_translate("w_perm_Analysis", "49"))
        item = self.tableFrequencies.item(49, 2)
        item.setText(_translate("w_perm_Analysis", "50"))
        self.tableFrequencies.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("w_perm_Analysis", "Number of shuffles"))
        self.buttonExtra.setText(_translate("w_perm_Analysis", "Plot Extra"))
        self.label.setText(_translate("w_perm_Analysis", "Min Y axis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("w_perm_Analysis", "Permutation Analysis"))

