# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_perm_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_w_perm_Analysis(object):
    def setupUi(self, w_perm_Analysis):
        w_perm_Analysis.setObjectName("w_perm_Analysis")
        w_perm_Analysis.resize(925, 564)
        self.centralwidget = QtWidgets.QWidget(w_perm_Analysis)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(480, 101, 47, 13))
        self.label_24.setObjectName("label_24")
        self.ButtonRunAll = QtWidgets.QPushButton(self.tab)
        self.ButtonRunAll.setGeometry(QtCore.QRect(220, 116, 70, 51))
        self.ButtonRunAll.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonRunAll.setObjectName("ButtonRunAll")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(540, 117, 41, 16))
        self.label_18.setObjectName("label_18")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(705, 121, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(836, 119, 41, 16))
        self.label_15.setObjectName("label_15")
        self.spinShortChunksize = QtWidgets.QSpinBox(self.tab)
        self.spinShortChunksize.setGeometry(QtCore.QRect(705, 169, 42, 22))
        self.spinShortChunksize.setProperty("value", 12)
        self.spinShortChunksize.setObjectName("spinShortChunksize")
        self.Button2PDF = QtWidgets.QPushButton(self.tab)
        self.Button2PDF.setGeometry(QtCore.QRect(506, 138, 41, 19))
        self.Button2PDF.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PDF.setObjectName("Button2PDF")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(743, 100, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(765, 171, 47, 13))
        self.label_16.setObjectName("label_16")
        self.frame_Experimental = QtWidgets.QFrame(self.tab)
        self.frame_Experimental.setGeometry(QtCore.QRect(10, 20, 901, 71))
        self.frame_Experimental.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental.setObjectName("frame_Experimental")
        self.ButSelectFile = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButSelectFile.setGeometry(QtCore.QRect(60, 19, 111, 31))
        self.ButSelectFile.setObjectName("ButSelectFile")
        self.ButDelFile = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButDelFile.setGeometry(QtCore.QRect(750, 20, 112, 31))
        self.ButDelFile.setObjectName("ButDelFile")
        self.labelFileSelected = QtWidgets.QLabel(self.frame_Experimental)
        self.labelFileSelected.setGeometry(QtCore.QRect(190, 19, 541, 31))
        self.labelFileSelected.setText("")
        self.labelFileSelected.setObjectName("labelFileSelected")
        self.Button2PNG = QtWidgets.QPushButton(self.tab)
        self.Button2PNG.setGeometry(QtCore.QRect(567, 138, 41, 19))
        self.Button2PNG.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PNG.setObjectName("Button2PNG")
        self.spinShortProcesses = QtWidgets.QSpinBox(self.tab)
        self.spinShortProcesses.setGeometry(QtCore.QRect(705, 139, 42, 22))
        self.spinShortProcesses.setProperty("value", 12)
        self.spinShortProcesses.setObjectName("spinShortProcesses")
        self.ButtonClearFigures = QtWidgets.QPushButton(self.tab)
        self.ButtonClearFigures.setGeometry(QtCore.QRect(380, 120, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonClearFigures.setPalette(palette)
        self.ButtonClearFigures.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonClearFigures.setObjectName("ButtonClearFigures")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(370, 114, 251, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.spinLongChunksize = QtWidgets.QSpinBox(self.tab)
        self.spinLongChunksize.setGeometry(QtCore.QRect(833, 169, 42, 22))
        self.spinLongChunksize.setProperty("value", 24)
        self.spinLongChunksize.setObjectName("spinLongChunksize")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(758, 141, 71, 16))
        self.label_13.setObjectName("label_13")
        self.spinLongProcesses = QtWidgets.QSpinBox(self.tab)
        self.spinLongProcesses.setGeometry(QtCore.QRect(833, 139, 42, 22))
        self.spinLongProcesses.setProperty("value", 24)
        self.spinLongProcesses.setObjectName("spinLongProcesses")
        self.frame_parallel = QtWidgets.QFrame(self.tab)
        self.frame_parallel.setGeometry(QtCore.QRect(700, 114, 181, 81))
        self.frame_parallel.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_parallel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_parallel.setObjectName("frame_parallel")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(12, 197, 171, 16))
        self.label_21.setObjectName("label_21")
        self.tableFrequencies = QtWidgets.QTableWidget(self.tab)
        self.tableFrequencies.setGeometry(QtCore.QRect(10, 220, 901, 281))
        self.tableFrequencies.setRowCount(10)
        self.tableFrequencies.setColumnCount(8)
        self.tableFrequencies.setObjectName("tableFrequencies")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 2, item)
        self.tableFrequencies.horizontalHeader().setVisible(False)
        self.tableFrequencies.horizontalHeader().setHighlightSections(False)
        self.tableFrequencies.verticalHeader().setVisible(False)
        self.tableFrequencies.verticalHeader().setHighlightSections(False)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 131, 121, 16))
        self.label_2.setObjectName("label_2")
        self.BoxNumberShuffles = QtWidgets.QSpinBox(self.tab)
        self.BoxNumberShuffles.setGeometry(QtCore.QRect(120, 128, 61, 22))
        self.BoxNumberShuffles.setMaximum(50000)
        self.BoxNumberShuffles.setSingleStep(500)
        self.BoxNumberShuffles.setProperty("value", 5000)
        self.BoxNumberShuffles.setObjectName("BoxNumberShuffles")
        self.frame_parallel.raise_()
        self.frame_2.raise_()
        self.label_24.raise_()
        self.ButtonRunAll.raise_()
        self.label_18.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.spinShortChunksize.raise_()
        self.Button2PDF.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.frame_Experimental.raise_()
        self.Button2PNG.raise_()
        self.spinShortProcesses.raise_()
        self.ButtonClearFigures.raise_()
        self.spinLongChunksize.raise_()
        self.label_13.raise_()
        self.spinLongProcesses.raise_()
        self.label_21.raise_()
        self.tableFrequencies.raise_()
        self.label_2.raise_()
        self.BoxNumberShuffles.raise_()
        self.tabWidget.addTab(self.tab, "")
        w_perm_Analysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(w_perm_Analysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 21))
        self.menubar.setObjectName("menubar")
        w_perm_Analysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(w_perm_Analysis)
        self.statusbar.setObjectName("statusbar")
        w_perm_Analysis.setStatusBar(self.statusbar)

        self.retranslateUi(w_perm_Analysis)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(w_perm_Analysis)

    def retranslateUi(self, w_perm_Analysis):
        _translate = QtCore.QCoreApplication.translate
        w_perm_Analysis.setWindowTitle(_translate("w_perm_Analysis", "MainWindow"))
        self.label_24.setText(_translate("w_perm_Analysis", "FIGURES"))
        self.ButtonRunAll.setText(_translate("w_perm_Analysis", "RUN"))
        self.label_18.setText(_translate("w_perm_Analysis", "Export"))
        self.label_14.setText(_translate("w_perm_Analysis", "Short d"))
        self.label_15.setText(_translate("w_perm_Analysis", "Lond d"))
        self.Button2PDF.setText(_translate("w_perm_Analysis", "PDF"))
        self.label_17.setText(_translate("w_perm_Analysis", "PARALLELIZATION"))
        self.label_16.setText(_translate("w_perm_Analysis", "chunksize"))
        self.ButSelectFile.setText(_translate("w_perm_Analysis", "Select file"))
        self.ButDelFile.setText(_translate("w_perm_Analysis", "Delete"))
        self.Button2PNG.setText(_translate("w_perm_Analysis", "PNG"))
        self.ButtonClearFigures.setText(_translate("w_perm_Analysis", "Close All"))
        self.label_13.setText(_translate("w_perm_Analysis", "# processes"))
        self.label_21.setText(_translate("w_perm_Analysis", "Frequency Analysis"))
        __sortingEnabled = self.tableFrequencies.isSortingEnabled()
        self.tableFrequencies.setSortingEnabled(False)
        item = self.tableFrequencies.item(0, 0)
        item.setText(_translate("w_perm_Analysis", "Interval Name"))
        item = self.tableFrequencies.item(0, 1)
        item.setText(_translate("w_perm_Analysis", "From (Hz)"))
        item = self.tableFrequencies.item(0, 2)
        item.setText(_translate("w_perm_Analysis", "To (Hz)"))
        item = self.tableFrequencies.item(0, 3)
        item.setText(_translate("w_perm_Analysis", "Short Distance"))
        item = self.tableFrequencies.item(0, 4)
        item.setText(_translate("w_perm_Analysis", "Long Distance"))
        item = self.tableFrequencies.item(0, 5)
        item.setText(_translate("w_perm_Analysis", "Ratio"))
        item = self.tableFrequencies.item(1, 0)
        item.setText(_translate("w_perm_Analysis", "Delta"))
        item = self.tableFrequencies.item(1, 1)
        item.setText(_translate("w_perm_Analysis", "1"))
        item = self.tableFrequencies.item(1, 2)
        item.setText(_translate("w_perm_Analysis", "4"))
        item = self.tableFrequencies.item(2, 0)
        item.setText(_translate("w_perm_Analysis", "Theta"))
        item = self.tableFrequencies.item(2, 1)
        item.setText(_translate("w_perm_Analysis", "6"))
        item = self.tableFrequencies.item(2, 2)
        item.setText(_translate("w_perm_Analysis", "10"))
        item = self.tableFrequencies.item(3, 0)
        item.setText(_translate("w_perm_Analysis", "Sigma"))
        item = self.tableFrequencies.item(3, 1)
        item.setText(_translate("w_perm_Analysis", "11"))
        item = self.tableFrequencies.item(3, 2)
        item.setText(_translate("w_perm_Analysis", "16"))
        item = self.tableFrequencies.item(4, 0)
        item.setText(_translate("w_perm_Analysis", "Gamma Low"))
        item = self.tableFrequencies.item(4, 1)
        item.setText(_translate("w_perm_Analysis", "30"))
        item = self.tableFrequencies.item(4, 2)
        item.setText(_translate("w_perm_Analysis", "50"))
        self.tableFrequencies.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("w_perm_Analysis", "Number of shuffles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("w_perm_Analysis", "Permutation Analysis"))

