# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_coherence.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window_Coherence(object):
    def setupUi(self, window_Coherence):
        window_Coherence.setObjectName("window_Coherence")
        window_Coherence.resize(933, 845)
        self.centralwidget = QtWidgets.QWidget(window_Coherence)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 821))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(520, 372, 61, 16))
        self.label_24.setObjectName("label_24")
        self.ButtonRunAll = QtWidgets.QPushButton(self.tab)
        self.ButtonRunAll.setGeometry(QtCore.QRect(404, 299, 101, 51))
        self.ButtonRunAll.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonRunAll.setObjectName("ButtonRunAll")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(30, 395, 131, 20))
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(580, 391, 41, 16))
        self.label_18.setObjectName("label_18")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(721, 260, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(852, 258, 41, 16))
        self.label_15.setObjectName("label_15")
        self.SpinBoxNeighborDist = QtWidgets.QDoubleSpinBox(self.tab)
        self.SpinBoxNeighborDist.setGeometry(QtCore.QRect(178, 370, 68, 20))
        self.SpinBoxNeighborDist.setSingleStep(0.5)
        self.SpinBoxNeighborDist.setProperty("value", 1.0)
        self.SpinBoxNeighborDist.setObjectName("SpinBoxNeighborDist")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(30, 345, 151, 20))
        self.label_12.setObjectName("label_12")
        self.spinShortChunksize = QtWidgets.QSpinBox(self.tab)
        self.spinShortChunksize.setGeometry(QtCore.QRect(721, 344, 42, 22))
        self.spinShortChunksize.setProperty("value", 12)
        self.spinShortChunksize.setObjectName("spinShortChunksize")
        self.spinBoxDownsampling = QtWidgets.QSpinBox(self.tab)
        self.spinBoxDownsampling.setGeometry(QtCore.QRect(206, 318, 41, 20))
        self.spinBoxDownsampling.setMinimum(1)
        self.spinBoxDownsampling.setMaximum(8)
        self.spinBoxDownsampling.setSingleStep(1)
        self.spinBoxDownsampling.setProperty("value", 2)
        self.spinBoxDownsampling.setDisplayIntegerBase(10)
        self.spinBoxDownsampling.setObjectName("spinBoxDownsampling")
        self.Button2PDF = QtWidgets.QPushButton(self.tab)
        self.Button2PDF.setGeometry(QtCore.QRect(546, 412, 41, 19))
        self.Button2PDF.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PDF.setObjectName("Button2PDF")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(31, 318, 151, 20))
        self.label_11.setObjectName("label_11")
        self.frame_Control = QtWidgets.QFrame(self.tab)
        self.frame_Control.setGeometry(QtCore.QRect(10, 130, 901, 101))
        self.frame_Control.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Control.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Control.setObjectName("frame_Control")
        self.listWidget_Control = QtWidgets.QListWidget(self.frame_Control)
        self.listWidget_Control.setGeometry(QtCore.QRect(170, 20, 691, 61))
        self.listWidget_Control.setObjectName("listWidget_Control")
        self.ButtonAddControlFolder = QtWidgets.QPushButton(self.frame_Control)
        self.ButtonAddControlFolder.setGeometry(QtCore.QRect(60, 19, 111, 31))
        self.ButtonAddControlFolder.setObjectName("ButtonAddControlFolder")
        self.ButtonDeleteControlFolder = QtWidgets.QPushButton(self.frame_Control)
        self.ButtonDeleteControlFolder.setGeometry(QtCore.QRect(59, 51, 112, 31))
        self.ButtonDeleteControlFolder.setObjectName("ButtonDeleteControlFolder")
        self.label_6 = QtWidgets.QLabel(self.frame_Control)
        self.label_6.setGeometry(QtCore.QRect(-10, 0, 51, 31))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(281, 302, 111, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButtonWake = QtWidgets.QRadioButton(self.frame)
        self.radioButtonWake.setEnabled(True)
        self.radioButtonWake.setGeometry(QtCore.QRect(8, 5, 119, 23))
        self.radioButtonWake.setChecked(False)
        self.radioButtonWake.setObjectName("radioButtonWake")
        self.radioButtonNoREM = QtWidgets.QRadioButton(self.frame)
        self.radioButtonNoREM.setGeometry(QtCore.QRect(8, 27, 119, 23))
        self.radioButtonNoREM.setAutoExclusive(True)
        self.radioButtonNoREM.setObjectName("radioButtonNoREM")
        self.radioButtonREM = QtWidgets.QRadioButton(self.frame)
        self.radioButtonREM.setGeometry(QtCore.QRect(8, 50, 119, 23))
        self.radioButtonREM.setChecked(True)
        self.radioButtonREM.setAutoExclusive(True)
        self.radioButtonREM.setObjectName("radioButtonREM")
        self.radioButtonConvulsion = QtWidgets.QRadioButton(self.frame)
        self.radioButtonConvulsion.setEnabled(True)
        self.radioButtonConvulsion.setGeometry(QtCore.QRect(8, 114, 119, 23))
        self.radioButtonConvulsion.setObjectName("radioButtonConvulsion")
        self.radioButtonSleeping = QtWidgets.QRadioButton(self.frame)
        self.radioButtonSleeping.setEnabled(True)
        self.radioButtonSleeping.setGeometry(QtCore.QRect(8, 74, 82, 17))
        self.radioButtonSleeping.setObjectName("radioButtonSleeping")
        self.radioButtonNonConvulsive = QtWidgets.QRadioButton(self.frame)
        self.radioButtonNonConvulsive.setEnabled(True)
        self.radioButtonNonConvulsive.setGeometry(QtCore.QRect(8, 96, 91, 17))
        self.radioButtonNonConvulsive.setObjectName("radioButtonNonConvulsive")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(750, 282, 121, 20))
        self.label_17.setObjectName("label_17")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(295, 284, 161, 21))
        self.label.setObjectName("label")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(771, 346, 71, 20))
        self.label_16.setObjectName("label_16")
        self.frame_Experimental = QtWidgets.QFrame(self.tab)
        self.frame_Experimental.setGeometry(QtCore.QRect(10, 20, 901, 101))
        self.frame_Experimental.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental.setObjectName("frame_Experimental")
        self.ButtonAddExpFolder = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButtonAddExpFolder.setGeometry(QtCore.QRect(60, 19, 111, 31))
        self.ButtonAddExpFolder.setObjectName("ButtonAddExpFolder")
        self.ButtonDeleteExpFolder = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButtonDeleteExpFolder.setGeometry(QtCore.QRect(59, 51, 112, 31))
        self.ButtonDeleteExpFolder.setObjectName("ButtonDeleteExpFolder")
        self.listWidget_Exp = QtWidgets.QListWidget(self.frame_Experimental)
        self.listWidget_Exp.setGeometry(QtCore.QRect(170, 20, 691, 61))
        self.listWidget_Exp.setObjectName("listWidget_Exp")
        self.label_2 = QtWidgets.QLabel(self.frame_Experimental)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 51, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setObjectName("label_2")
        self.Button2PNG = QtWidgets.QPushButton(self.tab)
        self.Button2PNG.setGeometry(QtCore.QRect(607, 412, 41, 19))
        self.Button2PNG.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PNG.setObjectName("Button2PNG")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 370, 141, 20))
        self.label_3.setObjectName("label_3")
        self.spinShortProcesses = QtWidgets.QSpinBox(self.tab)
        self.spinShortProcesses.setGeometry(QtCore.QRect(721, 314, 42, 22))
        self.spinShortProcesses.setProperty("value", 12)
        self.spinShortProcesses.setObjectName("spinShortProcesses")
        self.ButtonRunNewBS = QtWidgets.QPushButton(self.tab)
        self.ButtonRunNewBS.setEnabled(False)
        self.ButtonRunNewBS.setGeometry(QtCore.QRect(520, 300, 70, 51))
        self.ButtonRunNewBS.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.ButtonRunNewBS.setObjectName("ButtonRunNewBS")
        self.ButtonClearFigures = QtWidgets.QPushButton(self.tab)
        self.ButtonClearFigures.setGeometry(QtCore.QRect(420, 394, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonClearFigures.setPalette(palette)
        self.ButtonClearFigures.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonClearFigures.setObjectName("ButtonClearFigures")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(688, 422, 151, 20))
        self.label_19.setObjectName("label_19")
        self.SpinBoxLongDist = QtWidgets.QDoubleSpinBox(self.tab)
        self.SpinBoxLongDist.setGeometry(QtCore.QRect(178, 395, 68, 20))
        self.SpinBoxLongDist.setSingleStep(0.5)
        self.SpinBoxLongDist.setProperty("value", 3.0)
        self.SpinBoxLongDist.setObjectName("SpinBoxLongDist")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(410, 388, 251, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.spinLongChunksize = QtWidgets.QSpinBox(self.tab)
        self.spinLongChunksize.setGeometry(QtCore.QRect(849, 344, 42, 22))
        self.spinLongChunksize.setProperty("value", 24)
        self.spinLongChunksize.setObjectName("spinLongChunksize")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(764, 316, 81, 20))
        self.label_13.setObjectName("label_13")
        self.frame_montage = QtWidgets.QFrame(self.tab)
        self.frame_montage.setGeometry(QtCore.QRect(20, 419, 251, 21))
        self.frame_montage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_montage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_montage.setObjectName("frame_montage")
        self.radioButtonRealDistances = QtWidgets.QRadioButton(self.frame_montage)
        self.radioButtonRealDistances.setGeometry(QtCore.QRect(106, 0, 61, 23))
        self.radioButtonRealDistances.setObjectName("radioButtonRealDistances")
        self.label_10 = QtWidgets.QLabel(self.frame_montage)
        self.label_10.setGeometry(QtCore.QRect(7, 0, 71, 20))
        self.label_10.setObjectName("label_10")
        self.radioButtonGrid = QtWidgets.QRadioButton(self.frame_montage)
        self.radioButtonGrid.setGeometry(QtCore.QRect(176, 0, 61, 23))
        self.radioButtonGrid.setChecked(True)
        self.radioButtonGrid.setObjectName("radioButtonGrid")
        self.spinLongProcesses = QtWidgets.QSpinBox(self.tab)
        self.spinLongProcesses.setGeometry(QtCore.QRect(849, 314, 42, 22))
        self.spinLongProcesses.setProperty("value", 24)
        self.spinLongProcesses.setObjectName("spinLongProcesses")
        self.frame_parallel = QtWidgets.QFrame(self.tab)
        self.frame_parallel.setGeometry(QtCore.QRect(716, 298, 181, 81))
        self.frame_parallel.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_parallel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_parallel.setObjectName("frame_parallel")
        self.spinBoxNotchQ = QtWidgets.QSpinBox(self.tab)
        self.spinBoxNotchQ.setGeometry(QtCore.QRect(852, 419, 42, 22))
        self.spinBoxNotchQ.setProperty("value", 20)
        self.spinBoxNotchQ.setObjectName("spinBoxNotchQ")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(15, 489, 171, 16))
        self.label_21.setObjectName("label_21")
        self.tableFrequencies = QtWidgets.QTableWidget(self.tab)
        self.tableFrequencies.setGeometry(QtCore.QRect(10, 510, 901, 271))
        self.tableFrequencies.setRowCount(10)
        self.tableFrequencies.setColumnCount(8)
        self.tableFrequencies.setObjectName("tableFrequencies")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableFrequencies.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableFrequencies.setItem(9, 2, item)
        self.tableFrequencies.horizontalHeader().setVisible(False)
        self.tableFrequencies.horizontalHeader().setHighlightSections(False)
        self.tableFrequencies.verticalHeader().setVisible(False)
        self.tableFrequencies.verticalHeader().setHighlightSections(False)
        self.ButtonRunNewFreqs = QtWidgets.QPushButton(self.tab)
        self.ButtonRunNewFreqs.setEnabled(False)
        self.ButtonRunNewFreqs.setGeometry(QtCore.QRect(605, 300, 81, 51))
        self.ButtonRunNewFreqs.setStyleSheet("background-color: rgb(38, 255, 38);")
        self.ButtonRunNewFreqs.setObjectName("ButtonRunNewFreqs")
        self.frame_coherence = QtWidgets.QFrame(self.tab)
        self.frame_coherence.setGeometry(QtCore.QRect(20, 289, 231, 25))
        self.frame_coherence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_coherence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_coherence.setObjectName("frame_coherence")
        self.label_27 = QtWidgets.QLabel(self.frame_coherence)
        self.label_27.setGeometry(QtCore.QRect(8, 4, 101, 16))
        self.label_27.setObjectName("label_27")
        self.rbcohabs = QtWidgets.QRadioButton(self.frame_coherence)
        self.rbcohabs.setGeometry(QtCore.QRect(93, 4, 61, 17))
        self.rbcohabs.setChecked(False)
        self.rbcohabs.setObjectName("rbcohabs")
        self.rbcohimag = QtWidgets.QRadioButton(self.frame_coherence)
        self.rbcohimag.setGeometry(QtCore.QRect(153, 4, 82, 17))
        self.rbcohimag.setChecked(True)
        self.rbcohimag.setObjectName("rbcohimag")
        self.checkBoxExploratoryAnalysis = QtWidgets.QCheckBox(self.tab)
        self.checkBoxExploratoryAnalysis.setGeometry(QtCore.QRect(10, 246, 151, 20))
        self.checkBoxExploratoryAnalysis.setObjectName("checkBoxExploratoryAnalysis")
        self.listWidget_destfolder = QtWidgets.QListWidget(self.tab)
        self.listWidget_destfolder.setGeometry(QtCore.QRect(337, 240, 571, 31))
        self.listWidget_destfolder.setObjectName("listWidget_destfolder")
        self.pbdestfolder = QtWidgets.QPushButton(self.tab)
        self.pbdestfolder.setGeometry(QtCore.QRect(178, 240, 161, 31))
        self.pbdestfolder.setObjectName("pbdestfolder")
        self.frame_montage_3 = QtWidgets.QFrame(self.tab)
        self.frame_montage_3.setGeometry(QtCore.QRect(19, 451, 251, 21))
        self.frame_montage_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_montage_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_montage_3.setObjectName("frame_montage_3")
        self.radioButtonOpenEphys = QtWidgets.QRadioButton(self.frame_montage_3)
        self.radioButtonOpenEphys.setGeometry(QtCore.QRect(106, 0, 61, 23))
        self.radioButtonOpenEphys.setObjectName("radioButtonOpenEphys")
        self.label_56 = QtWidgets.QLabel(self.frame_montage_3)
        self.label_56.setGeometry(QtCore.QRect(7, 0, 71, 20))
        self.label_56.setObjectName("label_56")
        self.radioButtonTaini = QtWidgets.QRadioButton(self.frame_montage_3)
        self.radioButtonTaini.setGeometry(QtCore.QRect(176, 0, 61, 23))
        self.radioButtonTaini.setChecked(True)
        self.radioButtonTaini.setObjectName("radioButtonTaini")
        self.spinBoxSamplingRate = QtWidgets.QDoubleSpinBox(self.tab)
        self.spinBoxSamplingRate.setGeometry(QtCore.QRect(175, 340, 71, 24))
        self.spinBoxSamplingRate.setMaximum(10000.0)
        self.spinBoxSamplingRate.setSingleStep(50.0)
        self.spinBoxSamplingRate.setProperty("value", 254.41)
        self.spinBoxSamplingRate.setObjectName("spinBoxSamplingRate")
        self.frame_coherence.raise_()
        self.frame_parallel.raise_()
        self.frame_2.raise_()
        self.label_24.raise_()
        self.ButtonRunAll.raise_()
        self.label_9.raise_()
        self.label_18.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.SpinBoxNeighborDist.raise_()
        self.label_12.raise_()
        self.spinShortChunksize.raise_()
        self.spinBoxDownsampling.raise_()
        self.Button2PDF.raise_()
        self.label_11.raise_()
        self.frame_Control.raise_()
        self.frame.raise_()
        self.label_17.raise_()
        self.label.raise_()
        self.label_16.raise_()
        self.frame_Experimental.raise_()
        self.Button2PNG.raise_()
        self.label_3.raise_()
        self.spinShortProcesses.raise_()
        self.ButtonRunNewBS.raise_()
        self.ButtonClearFigures.raise_()
        self.label_19.raise_()
        self.SpinBoxLongDist.raise_()
        self.spinLongChunksize.raise_()
        self.label_13.raise_()
        self.frame_montage.raise_()
        self.spinLongProcesses.raise_()
        self.spinBoxNotchQ.raise_()
        self.label_21.raise_()
        self.tableFrequencies.raise_()
        self.ButtonRunNewFreqs.raise_()
        self.checkBoxExploratoryAnalysis.raise_()
        self.listWidget_destfolder.raise_()
        self.pbdestfolder.raise_()
        self.frame_montage_3.raise_()
        self.spinBoxSamplingRate.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_Experimental_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_Experimental_2.setGeometry(QtCore.QRect(10, 8, 701, 81))
        self.frame_Experimental_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental_2.setObjectName("frame_Experimental_2")
        self.ButtonAdd_IndRecords = QtWidgets.QPushButton(self.frame_Experimental_2)
        self.ButtonAdd_IndRecords.setGeometry(QtCore.QRect(10, 9, 111, 31))
        self.ButtonAdd_IndRecords.setObjectName("ButtonAdd_IndRecords")
        self.ButtonDelete_IndRecords = QtWidgets.QPushButton(self.frame_Experimental_2)
        self.ButtonDelete_IndRecords.setGeometry(QtCore.QRect(9, 41, 112, 31))
        self.ButtonDelete_IndRecords.setObjectName("ButtonDelete_IndRecords")
        self.listWidget_Indiv_recordings = QtWidgets.QListWidget(self.frame_Experimental_2)
        self.listWidget_Indiv_recordings.setGeometry(QtCore.QRect(120, 10, 571, 61))
        self.listWidget_Indiv_recordings.setObjectName("listWidget_Indiv_recordings")
        self.ButtonLoadRecordings = QtWidgets.QPushButton(self.tab_2)
        self.ButtonLoadRecordings.setGeometry(QtCore.QRect(740, 40, 151, 51))
        self.ButtonLoadRecordings.setObjectName("ButtonLoadRecordings")
        self.ScrollBarCurrentRecord = QtWidgets.QScrollBar(self.tab_2)
        self.ScrollBarCurrentRecord.setGeometry(QtCore.QRect(10, 96, 81, 31))
        self.ScrollBarCurrentRecord.setOrientation(QtCore.Qt.Horizontal)
        self.ScrollBarCurrentRecord.setObjectName("ScrollBarCurrentRecord")
        self.ButtonCloseFigures = QtWidgets.QPushButton(self.tab_2)
        self.ButtonCloseFigures.setGeometry(QtCore.QRect(553, 270, 80, 51))
        self.ButtonCloseFigures.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonCloseFigures.setObjectName("ButtonCloseFigures")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(547, 146, 91, 20))
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setObjectName("label_4")
        self.ButtonExportIndPDF = QtWidgets.QPushButton(self.tab_2)
        self.ButtonExportIndPDF.setGeometry(QtCore.QRect(553, 180, 80, 31))
        self.ButtonExportIndPDF.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.ButtonExportIndPDF.setObjectName("ButtonExportIndPDF")
        self.ButtonExportIndPNG = QtWidgets.QPushButton(self.tab_2)
        self.ButtonExportIndPNG.setGeometry(QtCore.QRect(553, 220, 80, 31))
        self.ButtonExportIndPNG.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.ButtonExportIndPNG.setObjectName("ButtonExportIndPNG")
        self.ButtonPlotRawData = QtWidgets.QPushButton(self.tab_2)
        self.ButtonPlotRawData.setGeometry(QtCore.QRect(200, 170, 91, 41))
        self.ButtonPlotRawData.setObjectName("ButtonPlotRawData")
        self.ButtonCoherogram = QtWidgets.QPushButton(self.tab_2)
        self.ButtonCoherogram.setEnabled(False)
        self.ButtonCoherogram.setGeometry(QtCore.QRect(200, 310, 91, 41))
        self.ButtonCoherogram.setObjectName("ButtonCoherogram")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setEnabled(True)
        self.label_20.setGeometry(QtCore.QRect(742, 10, 81, 20))
        self.label_20.setObjectName("label_20")
        self.spinBoxDownsampling_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxDownsampling_2.setEnabled(True)
        self.spinBoxDownsampling_2.setGeometry(QtCore.QRect(850, 10, 41, 20))
        self.spinBoxDownsampling_2.setMinimum(1)
        self.spinBoxDownsampling_2.setMaximum(64)
        self.spinBoxDownsampling_2.setProperty("value", 4)
        self.spinBoxDownsampling_2.setObjectName("spinBoxDownsampling_2")
        self.labelCurrentRecording = QtWidgets.QLabel(self.tab_2)
        self.labelCurrentRecording.setGeometry(QtCore.QRect(100, 96, 411, 31))
        self.labelCurrentRecording.setText("")
        self.labelCurrentRecording.setObjectName("labelCurrentRecording")
        self.ButtonPlotPS = QtWidgets.QPushButton(self.tab_2)
        self.ButtonPlotPS.setGeometry(QtCore.QRect(200, 220, 91, 41))
        self.ButtonPlotPS.setObjectName("ButtonPlotPS")
        self.BoxBinSize = QtWidgets.QSpinBox(self.tab_2)
        self.BoxBinSize.setGeometry(QtCore.QRect(10, 180, 71, 22))
        self.BoxBinSize.setMaximum(600000)
        self.BoxBinSize.setSingleStep(30)
        self.BoxBinSize.setProperty("value", 30)
        self.BoxBinSize.setObjectName("BoxBinSize")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(87, 180, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(377, 144, 111, 20))
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setObjectName("label_7")
        self.BoxTmin = QtWidgets.QSpinBox(self.tab_2)
        self.BoxTmin.setGeometry(QtCore.QRect(10, 210, 71, 22))
        self.BoxTmin.setMaximum(6000000)
        self.BoxTmin.setSingleStep(60)
        self.BoxTmin.setObjectName("BoxTmin")
        self.BoxTmax = QtWidgets.QSpinBox(self.tab_2)
        self.BoxTmax.setGeometry(QtCore.QRect(10, 240, 71, 22))
        self.BoxTmax.setMaximum(6000000)
        self.BoxTmax.setSingleStep(60)
        self.BoxTmax.setProperty("value", 1)
        self.BoxTmax.setObjectName("BoxTmax")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(88, 214, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(89, 242, 47, 13))
        self.label_22.setObjectName("label_22")
        self.tableExportToExcel = QtWidgets.QTableView(self.tab_2)
        self.tableExportToExcel.setGeometry(QtCore.QRect(660, 150, 256, 391))
        self.tableExportToExcel.setObjectName("tableExportToExcel")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(660, 128, 101, 16))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setEnabled(False)
        self.label_25.setGeometry(QtCore.QRect(10, 322, 171, 16))
        self.label_25.setObjectName("label_25")
        self.ButtonExportToExcel = QtWidgets.QPushButton(self.tab_2)
        self.ButtonExportToExcel.setGeometry(QtCore.QRect(660, 550, 75, 23))
        self.ButtonExportToExcel.setObjectName("ButtonExportToExcel")
        self.e_11 = QtWidgets.QRadioButton(self.tab_2)
        self.e_11.setGeometry(QtCore.QRect(360, 270, 16, 17))
        self.e_11.setText("")
        self.e_11.setAutoExclusive(False)
        self.e_11.setObjectName("e_11")
        self.e_14 = QtWidgets.QRadioButton(self.tab_2)
        self.e_14.setGeometry(QtCore.QRect(390, 220, 16, 17))
        self.e_14.setText("")
        self.e_14.setChecked(True)
        self.e_14.setAutoExclusive(False)
        self.e_14.setObjectName("e_14")
        self.e_1 = QtWidgets.QRadioButton(self.tab_2)
        self.e_1.setGeometry(QtCore.QRect(350, 320, 16, 17))
        self.e_1.setText("")
        self.e_1.setAutoExclusive(False)
        self.e_1.setObjectName("e_1")
        self.e_12 = QtWidgets.QRadioButton(self.tab_2)
        self.e_12.setGeometry(QtCore.QRect(380, 250, 16, 17))
        self.e_12.setText("")
        self.e_12.setAutoExclusive(False)
        self.e_12.setObjectName("e_12")
        self.e_9 = QtWidgets.QRadioButton(self.tab_2)
        self.e_9.setGeometry(QtCore.QRect(380, 290, 16, 17))
        self.e_9.setText("")
        self.e_9.setAutoExclusive(False)
        self.e_9.setObjectName("e_9")
        self.e_4 = QtWidgets.QRadioButton(self.tab_2)
        self.e_4.setGeometry(QtCore.QRect(350, 350, 16, 17))
        self.e_4.setText("")
        self.e_4.setAutoExclusive(False)
        self.e_4.setObjectName("e_4")
        self.e_7 = QtWidgets.QRadioButton(self.tab_2)
        self.e_7.setGeometry(QtCore.QRect(350, 380, 16, 17))
        self.e_7.setText("")
        self.e_7.setAutoExclusive(False)
        self.e_7.setObjectName("e_7")
        self.e_0 = QtWidgets.QRadioButton(self.tab_2)
        self.e_0.setGeometry(QtCore.QRect(380, 320, 16, 17))
        self.e_0.setText("")
        self.e_0.setAutoExclusive(False)
        self.e_0.setObjectName("e_0")
        self.e_3 = QtWidgets.QRadioButton(self.tab_2)
        self.e_3.setGeometry(QtCore.QRect(380, 350, 16, 17))
        self.e_3.setText("")
        self.e_3.setAutoExclusive(False)
        self.e_3.setObjectName("e_3")
        self.e_15 = QtWidgets.QRadioButton(self.tab_2)
        self.e_15.setGeometry(QtCore.QRect(410, 220, 16, 17))
        self.e_15.setText("")
        self.e_15.setAutoExclusive(False)
        self.e_15.setObjectName("e_15")
        self.e_13 = QtWidgets.QRadioButton(self.tab_2)
        self.e_13.setGeometry(QtCore.QRect(410, 250, 16, 17))
        self.e_13.setText("")
        self.e_13.setAutoExclusive(False)
        self.e_13.setObjectName("e_13")
        self.e_8 = QtWidgets.QRadioButton(self.tab_2)
        self.e_8.setGeometry(QtCore.QRect(410, 320, 16, 17))
        self.e_8.setText("")
        self.e_8.setAutoExclusive(False)
        self.e_8.setObjectName("e_8")
        self.e_10 = QtWidgets.QRadioButton(self.tab_2)
        self.e_10.setGeometry(QtCore.QRect(410, 290, 16, 17))
        self.e_10.setText("")
        self.e_10.setAutoExclusive(False)
        self.e_10.setObjectName("e_10")
        self.e_2 = QtWidgets.QRadioButton(self.tab_2)
        self.e_2.setGeometry(QtCore.QRect(410, 350, 16, 17))
        self.e_2.setText("")
        self.e_2.setAutoExclusive(False)
        self.e_2.setObjectName("e_2")
        self.e_6 = QtWidgets.QRadioButton(self.tab_2)
        self.e_6.setGeometry(QtCore.QRect(380, 380, 16, 17))
        self.e_6.setText("")
        self.e_6.setAutoExclusive(False)
        self.e_6.setObjectName("e_6")
        self.e_5 = QtWidgets.QRadioButton(self.tab_2)
        self.e_5.setGeometry(QtCore.QRect(410, 380, 16, 17))
        self.e_5.setText("")
        self.e_5.setAutoExclusive(False)
        self.e_5.setObjectName("e_5")
        self.e_29 = QtWidgets.QRadioButton(self.tab_2)
        self.e_29.setGeometry(QtCore.QRect(440, 350, 16, 17))
        self.e_29.setText("")
        self.e_29.setAutoExclusive(False)
        self.e_29.setObjectName("e_29")
        self.e_18 = QtWidgets.QRadioButton(self.tab_2)
        self.e_18.setGeometry(QtCore.QRect(440, 250, 16, 17))
        self.e_18.setText("")
        self.e_18.setAutoExclusive(False)
        self.e_18.setObjectName("e_18")
        self.e_21 = QtWidgets.QRadioButton(self.tab_2)
        self.e_21.setGeometry(QtCore.QRect(440, 290, 16, 17))
        self.e_21.setText("")
        self.e_21.setAutoExclusive(False)
        self.e_21.setObjectName("e_21")
        self.e_23 = QtWidgets.QRadioButton(self.tab_2)
        self.e_23.setGeometry(QtCore.QRect(440, 320, 16, 17))
        self.e_23.setText("")
        self.e_23.setAutoExclusive(False)
        self.e_23.setObjectName("e_23")
        self.e_16 = QtWidgets.QRadioButton(self.tab_2)
        self.e_16.setGeometry(QtCore.QRect(440, 220, 16, 17))
        self.e_16.setText("")
        self.e_16.setAutoExclusive(False)
        self.e_16.setObjectName("e_16")
        self.e_26 = QtWidgets.QRadioButton(self.tab_2)
        self.e_26.setGeometry(QtCore.QRect(440, 380, 16, 17))
        self.e_26.setText("")
        self.e_26.setAutoExclusive(False)
        self.e_26.setObjectName("e_26")
        self.e_28 = QtWidgets.QRadioButton(self.tab_2)
        self.e_28.setGeometry(QtCore.QRect(470, 350, 16, 17))
        self.e_28.setText("")
        self.e_28.setAutoExclusive(False)
        self.e_28.setObjectName("e_28")
        self.e_31 = QtWidgets.QRadioButton(self.tab_2)
        self.e_31.setGeometry(QtCore.QRect(470, 320, 16, 17))
        self.e_31.setText("")
        self.e_31.setObjectName("e_31")
        self.e_17 = QtWidgets.QRadioButton(self.tab_2)
        self.e_17.setGeometry(QtCore.QRect(460, 220, 16, 17))
        self.e_17.setToolTipDuration(10)
        self.e_17.setWhatsThis("")
        self.e_17.setAccessibleName("")
        self.e_17.setAccessibleDescription("")
        self.e_17.setText("")
        self.e_17.setAutoExclusive(False)
        self.e_17.setObjectName("e_17")
        self.e_19 = QtWidgets.QRadioButton(self.tab_2)
        self.e_19.setGeometry(QtCore.QRect(470, 250, 16, 17))
        self.e_19.setText("")
        self.e_19.setAutoExclusive(False)
        self.e_19.setObjectName("e_19")
        self.e_25 = QtWidgets.QRadioButton(self.tab_2)
        self.e_25.setGeometry(QtCore.QRect(470, 380, 16, 17))
        self.e_25.setText("")
        self.e_25.setAutoExclusive(False)
        self.e_25.setObjectName("e_25")
        self.e_22 = QtWidgets.QRadioButton(self.tab_2)
        self.e_22.setGeometry(QtCore.QRect(470, 290, 16, 17))
        self.e_22.setText("")
        self.e_22.setAutoExclusive(False)
        self.e_22.setObjectName("e_22")
        self.e_27 = QtWidgets.QRadioButton(self.tab_2)
        self.e_27.setGeometry(QtCore.QRect(500, 350, 16, 17))
        self.e_27.setText("")
        self.e_27.setAutoExclusive(False)
        self.e_27.setObjectName("e_27")
        self.e_30 = QtWidgets.QRadioButton(self.tab_2)
        self.e_30.setGeometry(QtCore.QRect(500, 320, 16, 17))
        self.e_30.setText("")
        self.e_30.setAutoExclusive(False)
        self.e_30.setObjectName("e_30")
        self.e_20 = QtWidgets.QRadioButton(self.tab_2)
        self.e_20.setGeometry(QtCore.QRect(490, 270, 16, 17))
        self.e_20.setText("")
        self.e_20.setAutoExclusive(False)
        self.e_20.setObjectName("e_20")
        self.e_24 = QtWidgets.QRadioButton(self.tab_2)
        self.e_24.setGeometry(QtCore.QRect(500, 380, 16, 17))
        self.e_24.setText("")
        self.e_24.setAutoExclusive(False)
        self.e_24.setObjectName("e_24")
        self.radioSelectAll = QtWidgets.QRadioButton(self.tab_2)
        self.radioSelectAll.setGeometry(QtCore.QRect(345, 170, 82, 17))
        self.radioSelectAll.setObjectName("radioSelectAll")
        self.radioSelectNone = QtWidgets.QRadioButton(self.tab_2)
        self.radioSelectNone.setGeometry(QtCore.QRect(345, 190, 82, 17))
        self.radioSelectNone.setObjectName("radioSelectNone")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(340, 210, 181, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.radioSelectLeftHem = QtWidgets.QRadioButton(self.tab_2)
        self.radioSelectLeftHem.setGeometry(QtCore.QRect(448, 170, 71, 17))
        self.radioSelectLeftHem.setObjectName("radioSelectLeftHem")
        self.radioSelectRightHem = QtWidgets.QRadioButton(self.tab_2)
        self.radioSelectRightHem.setGeometry(QtCore.QRect(448, 190, 71, 17))
        self.radioSelectRightHem.setObjectName("radioSelectRightHem")
        self.label_Tmax = QtWidgets.QLabel(self.tab_2)
        self.label_Tmax.setGeometry(QtCore.QRect(124, 243, 47, 13))
        self.label_Tmax.setText("")
        self.label_Tmax.setObjectName("label_Tmax")
        self.frame_3.raise_()
        self.frame_Experimental_2.raise_()
        self.ButtonLoadRecordings.raise_()
        self.ScrollBarCurrentRecord.raise_()
        self.ButtonCloseFigures.raise_()
        self.label_4.raise_()
        self.ButtonExportIndPDF.raise_()
        self.ButtonExportIndPNG.raise_()
        self.ButtonPlotRawData.raise_()
        self.ButtonCoherogram.raise_()
        self.label_20.raise_()
        self.spinBoxDownsampling_2.raise_()
        self.labelCurrentRecording.raise_()
        self.ButtonPlotPS.raise_()
        self.BoxBinSize.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.BoxTmin.raise_()
        self.BoxTmax.raise_()
        self.label_8.raise_()
        self.label_22.raise_()
        self.tableExportToExcel.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.ButtonExportToExcel.raise_()
        self.e_11.raise_()
        self.e_14.raise_()
        self.e_1.raise_()
        self.e_12.raise_()
        self.e_9.raise_()
        self.e_4.raise_()
        self.e_7.raise_()
        self.e_0.raise_()
        self.e_3.raise_()
        self.e_15.raise_()
        self.e_13.raise_()
        self.e_8.raise_()
        self.e_10.raise_()
        self.e_2.raise_()
        self.e_6.raise_()
        self.e_5.raise_()
        self.e_29.raise_()
        self.e_18.raise_()
        self.e_21.raise_()
        self.e_23.raise_()
        self.e_16.raise_()
        self.e_26.raise_()
        self.e_28.raise_()
        self.e_31.raise_()
        self.e_17.raise_()
        self.e_19.raise_()
        self.e_25.raise_()
        self.e_22.raise_()
        self.e_27.raise_()
        self.e_30.raise_()
        self.e_20.raise_()
        self.e_24.raise_()
        self.radioSelectAll.raise_()
        self.radioSelectNone.raise_()
        self.radioSelectLeftHem.raise_()
        self.radioSelectRightHem.raise_()
        self.label_Tmax.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        window_Coherence.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window_Coherence)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 20))
        self.menubar.setObjectName("menubar")
        window_Coherence.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window_Coherence)
        self.statusbar.setObjectName("statusbar")
        window_Coherence.setStatusBar(self.statusbar)

        self.retranslateUi(window_Coherence)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window_Coherence)

    def retranslateUi(self, window_Coherence):
        _translate = QtCore.QCoreApplication.translate
        window_Coherence.setWindowTitle(_translate("window_Coherence", "MainWindow"))
        self.label_24.setText(_translate("window_Coherence", "FIGURES"))
        self.ButtonRunAll.setText(_translate("window_Coherence", "LOAD and RUN"))
        self.label_9.setText(_translate("window_Coherence", "Long distance"))
        self.label_18.setText(_translate("window_Coherence", "Export"))
        self.label_14.setText(_translate("window_Coherence", "Short d"))
        self.label_15.setText(_translate("window_Coherence", "Lond d"))
        self.label_12.setText(_translate("window_Coherence", "Sampling Rate"))
        self.Button2PDF.setText(_translate("window_Coherence", "PDF"))
        self.label_11.setText(_translate("window_Coherence", "Downsampling"))
        self.ButtonAddControlFolder.setText(_translate("window_Coherence", "Add folder"))
        self.ButtonDeleteControlFolder.setText(_translate("window_Coherence", "Delete"))
        self.label_6.setText(_translate("window_Coherence", "   WT"))
        self.radioButtonWake.setText(_translate("window_Coherence", "Wake"))
        self.radioButtonNoREM.setText(_translate("window_Coherence", "No REM"))
        self.radioButtonREM.setText(_translate("window_Coherence", "REM"))
        self.radioButtonConvulsion.setText(_translate("window_Coherence", "Convulsion"))
        self.radioButtonSleeping.setText(_translate("window_Coherence", "Sleeping"))
        self.radioButtonNonConvulsive.setText(_translate("window_Coherence", "Non-convul"))
        self.label_17.setText(_translate("window_Coherence", "PARALLELIZATION"))
        self.label.setText(_translate("window_Coherence", "BRAIN STATE"))
        self.label_16.setText(_translate("window_Coherence", "chunksize"))
        self.ButtonAddExpFolder.setText(_translate("window_Coherence", "Add folder"))
        self.ButtonDeleteExpFolder.setText(_translate("window_Coherence", "Delete"))
        self.label_2.setText(_translate("window_Coherence", "   KO"))
        self.Button2PNG.setText(_translate("window_Coherence", "PNG"))
        self.label_3.setText(_translate("window_Coherence", "Neighbour distance"))
        self.ButtonRunNewBS.setText(_translate("window_Coherence", "RUN"))
        self.ButtonClearFigures.setText(_translate("window_Coherence", "Close All"))
        self.label_19.setText(_translate("window_Coherence", "Notch filter Q (50Hz)"))
        self.label_13.setText(_translate("window_Coherence", "#processes"))
        self.radioButtonRealDistances.setText(_translate("window_Coherence", "Real"))
        self.label_10.setText(_translate("window_Coherence", "Montage"))
        self.radioButtonGrid.setText(_translate("window_Coherence", "Grid"))
        self.label_21.setText(_translate("window_Coherence", "Frequency Analysis"))
        __sortingEnabled = self.tableFrequencies.isSortingEnabled()
        self.tableFrequencies.setSortingEnabled(False)
        item = self.tableFrequencies.item(0, 0)
        item.setText(_translate("window_Coherence", "Interval Name"))
        item = self.tableFrequencies.item(0, 1)
        item.setText(_translate("window_Coherence", "From (Hz)"))
        item = self.tableFrequencies.item(0, 2)
        item.setText(_translate("window_Coherence", "To (Hz)"))
        item = self.tableFrequencies.item(0, 3)
        item.setText(_translate("window_Coherence", " T-test (Short)"))
        item = self.tableFrequencies.item(0, 4)
        item.setText(_translate("window_Coherence", "T-test (Long)"))
        item = self.tableFrequencies.item(0, 5)
        item.setText(_translate("window_Coherence", "T-test (Ratio)"))
        item = self.tableFrequencies.item(0, 6)
        item.setText(_translate("window_Coherence", "Anova"))
        item = self.tableFrequencies.item(0, 7)
        item.setText(_translate("window_Coherence", "T-Test Variability"))
        item = self.tableFrequencies.item(1, 0)
        item.setText(_translate("window_Coherence", "Overall"))
        item = self.tableFrequencies.item(1, 1)
        item.setText(_translate("window_Coherence", "0"))
        item = self.tableFrequencies.item(1, 2)
        item.setText(_translate("window_Coherence", "50"))
        item = self.tableFrequencies.item(2, 0)
        item.setText(_translate("window_Coherence", "2-10"))
        item = self.tableFrequencies.item(2, 1)
        item.setText(_translate("window_Coherence", "2"))
        item = self.tableFrequencies.item(2, 2)
        item.setText(_translate("window_Coherence", "10"))
        item = self.tableFrequencies.item(3, 0)
        item.setText(_translate("window_Coherence", "10-20"))
        item = self.tableFrequencies.item(3, 1)
        item.setText(_translate("window_Coherence", "10"))
        item = self.tableFrequencies.item(3, 2)
        item.setText(_translate("window_Coherence", "20"))
        item = self.tableFrequencies.item(4, 0)
        item.setText(_translate("window_Coherence", "20-30"))
        item = self.tableFrequencies.item(4, 1)
        item.setText(_translate("window_Coherence", "20"))
        item = self.tableFrequencies.item(4, 2)
        item.setText(_translate("window_Coherence", "30"))
        item = self.tableFrequencies.item(5, 0)
        item.setText(_translate("window_Coherence", "30-40"))
        item = self.tableFrequencies.item(5, 1)
        item.setText(_translate("window_Coherence", "30"))
        item = self.tableFrequencies.item(5, 2)
        item.setText(_translate("window_Coherence", "40"))
        item = self.tableFrequencies.item(6, 0)
        item.setText(_translate("window_Coherence", "40-50"))
        item = self.tableFrequencies.item(6, 1)
        item.setText(_translate("window_Coherence", "40"))
        item = self.tableFrequencies.item(6, 2)
        item.setText(_translate("window_Coherence", "50"))
        self.tableFrequencies.setSortingEnabled(__sortingEnabled)
        self.ButtonRunNewFreqs.setText(_translate("window_Coherence", "RUN (Freq) "))
        self.label_27.setText(_translate("window_Coherence", "Coherence"))
        self.rbcohabs.setText(_translate("window_Coherence", "Abs"))
        self.rbcohimag.setText(_translate("window_Coherence", "Imag"))
        self.checkBoxExploratoryAnalysis.setText(_translate("window_Coherence", "Exploratory analysis"))
        self.pbdestfolder.setText(_translate("window_Coherence", "Choose results folder"))
        self.radioButtonOpenEphys.setText(_translate("window_Coherence", "Ephys"))
        self.label_56.setText(_translate("window_Coherence", "Recording"))
        self.radioButtonTaini.setText(_translate("window_Coherence", "Taini"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("window_Coherence", "Coherence Analysis"))
        self.ButtonAdd_IndRecords.setText(_translate("window_Coherence", "Add folder"))
        self.ButtonDelete_IndRecords.setText(_translate("window_Coherence", "Delete"))
        self.ButtonLoadRecordings.setText(_translate("window_Coherence", "Load recordings"))
        self.ButtonCloseFigures.setText(_translate("window_Coherence", "Close Figures"))
        self.label_4.setText(_translate("window_Coherence", "<html><head/><body><p align=\"center\">Export Figures</p></body></html>"))
        self.ButtonExportIndPDF.setText(_translate("window_Coherence", "PDF"))
        self.ButtonExportIndPNG.setText(_translate("window_Coherence", "PNG"))
        self.ButtonPlotRawData.setText(_translate("window_Coherence", "Plot Raw_Data"))
        self.ButtonCoherogram.setText(_translate("window_Coherence", "Wavelet"))
        self.label_20.setText(_translate("window_Coherence", "Downsampling"))
        self.ButtonPlotPS.setText(_translate("window_Coherence", "Plot PS"))
        self.label_5.setText(_translate("window_Coherence", "Bin to plot (seconds)"))
        self.label_7.setText(_translate("window_Coherence", "<html><head/><body><p align=\"center\">Channels to show</p></body></html>"))
        self.label_8.setText(_translate("window_Coherence", "Tmin"))
        self.label_22.setText(_translate("window_Coherence", "Tmax"))
        self.label_23.setText(_translate("window_Coherence", "Export to Excel"))
        self.label_25.setText(_translate("window_Coherence", "When a single channel is selected"))
        self.ButtonExportToExcel.setText(_translate("window_Coherence", "Export"))
        self.e_14.setToolTip(_translate("window_Coherence", "<html><head/><body><p>M1_FrA_LEFT</p></body></html>"))
        self.e_17.setToolTip(_translate("window_Coherence", "M1_FrA_RIGHT"))
        self.e_17.setStatusTip(_translate("window_Coherence", "M1_FrA_RIGHT"))
        self.radioSelectAll.setText(_translate("window_Coherence", "Select all"))
        self.radioSelectNone.setText(_translate("window_Coherence", "Select none"))
        self.radioSelectLeftHem.setText(_translate("window_Coherence", "Left Hem"))
        self.radioSelectRightHem.setText(_translate("window_Coherence", "Right Hem"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("window_Coherence", "Single Recording Analysis"))

